### 컬럼 전처리 (순서 변수 / 더미 변수)

In [1]:
import pandas as pd
df = pd.read_csv("C:/Users/user/Desktop/자전거PM사고_청주.csv",encoding = 'cp949')
df.shape
#index가 뒤죽박죽인 것을 확인할 수 있음.
#인덱스 번호 error로 인한 오류 있었음. 
# df = df.reset_index() 코드로 해결함 (index 새로 설정)

(1823, 58)

In [2]:
df = df.reset_index() #인덱스 분리

In [3]:
df

,index,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
0,0,2020082200100432,2020082217,충북,청주시,1000111.0,1845339.0,토,주,경상,...,내리막,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1,1,2020080100100116,2020080109,충북,청주시,993596.0,1848445.0,토,주,경상,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
2,2,2020092600100236,2020092611,충북,청주시,995526.0,1847649.0,토,주,경상,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
3,3,2020121200100323,2020121217,충북,청주시,995679.0,1851636.0,토,주,경상,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
4,4,2020062700100313,2020062714,충북,청주시,993695.0,1848615.0,토,주,부상신고,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,2018041900,충북,청주시,998267.0,1852140.0,목,야,중상,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,1,0
1819,1819,2018071900100710,2018071923,충북,청주시,997198.0,1847791.0,목,야,경상,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1820,1820,2018011300100473,2018011320,충북,청주시,998501.0,1852654.0,토,야,경상,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1821,1821,2017102000100588,2017102018,충북,청주시,993500.0,1848011.0,금,야,경상,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1822,1822,2017091300100523,2017091318,충북,청주시,995354.0,1848473.0,수,야,경상,...,평지,맑음,포장,건조,교차로,교차로 - 오지이상,0,0,1,0

In [4]:
df.columns #컬럼명 확인

Index(['index', 'TAAS사고관리번호', '발생일시', '발생지_시도', '발생지_시군구', 'X_POINT',
       'Y_POINT', '요일', '주야', '사고내용', '사고유형_대분류', '사고유형_중분류', '사고유형', '성별가해자',
       '성별가해자_1', '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자',
       '보호장구가해자_대분류', '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자',
       '행동유형가해자_대분류', '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자',
       '가해자신체상해주부위', '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류',
       '당사자종별피해자', '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류',
       '차량용도피해자_중분류', '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부',
       '어린이보호구역_여부', '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태',
       '노면상태_대분류', '노면상태', '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수',
       '부상신고자수'],
      dtype='object')

In [5]:
df['발생일시']

0       2020082217
1       2020080109
2       2020092611
3       2020121217
4       2020062714
           ...
1818    2018041900
1819    2018071923
1820    2018011320
1821    2017102018
1822    2017091318
Name: 발생일시, Length: 1823, dtype: int64

In [6]:
# 발생일시 -> datetime 으로 변환 -> date 컬럼 생성후 발생일시 컬럼 삭제
# 날짜 변환
df['year'] = df['발생일시'].astype(str)

In [7]:
year = []
for i in range(len(df['year'])):
    a = df['year'][i][0:4]
    year.append(a)
df['year'] = year

In [8]:
df['year']

0       2020
1       2020
2       2020
3       2020
4       2020
        ...
1818    2018
1819    2018
1820    2018
1821    2017
1822    2017
Name: year, Length: 1823, dtype: object

In [9]:
#위와 동일한 원리로 생성
df['month'] = df['발생일시'].astype(str)
month = []
for i in range(len(df['month'])):
    a = df['month'][i][4:6]
    month.append(a)
df['month'] = month

In [10]:
df['day'] = df['발생일시'].astype(str)
day = []
for i in range(len(df['day'])):
    a = df['day'][i][6:8]
    day.append(a)
df['day'] = day

In [11]:
df['hour'] = df['발생일시'].astype(str)
hour = []
for i in range(len(df['hour'])):
    a = df['hour'][i][-2:]
    hour.append(a)
df['hour'] = hour

In [12]:
df['date'] = df['year'] + '-' + df['month'] + '-' + df['day'] + ' ' + df['hour'] + ':00:00'
df['date'] = pd.to_datetime(df['date']) #datetime 으로 변환

In [13]:
df['date']

0      2020-08-22 17:00:00
1      2020-08-01 09:00:00
2      2020-09-26 11:00:00
3      2020-12-12 17:00:00
4      2020-06-27 14:00:00
               ...
1818   2018-04-19 00:00:00
1819   2018-07-19 23:00:00
1820   2018-01-13 20:00:00
1821   2017-10-20 18:00:00
1822   2017-09-13 18:00:00
Name: date, Length: 1823, dtype: datetime64[ns]

In [14]:
df.drop('발생일시', axis = 1, inplace = True) #axis = 0 : 행 / axis = 1 : 열 /inplace=True : 원본에서 바로 바꾸기.

In [15]:
df.drop(['year','month','day','hour'], axis = 1, inplace = True) #여러개 한꺼번에 삭제시 대괄호

In [16]:
df.columns

Index(['index', 'TAAS사고관리번호', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '사고유형_대분류', '사고유형_중분류', '사고유형', '성별가해자', '성별가해자_1',
       '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자', '보호장구가해자_대분류',
       '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자', '행동유형가해자_대분류',
       '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자', '가해자신체상해주부위',
       '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류', '당사자종별피해자',
       '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류', '차량용도피해자_중분류',
       '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부', '어린이보호구역_여부',
       '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태', '노면상태_대분류', '노면상태',
       '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수', '부상신고자수', 'date'],
      dtype='object')

* 발생지_시도, 발생지_시군구 : 충청북도, 청주시 로 공통이므로 전처리 생략
* 'X_POINT', 'Y_POINT' : 좌표이므로 생략

In [17]:
#요일
df['요일'].unique()

array(['토', '금', '목', '수', '화', '월', '일'], dtype=object)

In [18]:
요일_dummies = pd.get_dummies(df['요일'])
요일_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 요일_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,경상자수,부상신고자수,date,금,목,수,월,일,토,화
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,토,주,경상,차대차,...,1,0,2020-08-22 17:00:00,0,0,0,0,0,1,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,토,주,경상,차대차,...,1,0,2020-08-01 09:00:00,0,0,0,0,0,1,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,토,주,경상,차대차,...,1,0,2020-09-26 11:00:00,0,0,0,0,0,1,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,토,주,경상,차대차,...,1,0,2020-12-12 17:00:00,0,0,0,0,0,1,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,토,주,부상신고,차대차,...,0,1,2020-06-27 14:00:00,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,목,야,중상,차대차,...,1,0,2018-04-19 00:00:00,0,1,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,목,야,경상,차대차,...,1,0,2018-07-19 23:00:00,0,1,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,토,야,경상,차대차,...,1,0,2018-01-13 20:00:00,0,0,0,0,0,1,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,금,야,경상,차대차,...,1,0,2017-10-20 18:00:00,1,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,수,야,경상,차대차,...,1,0,2017-09-13 18:00:00,0,0,1,0,0,0,0

In [19]:
df['주야'].unique()

array(['주', '야'], dtype=object)

In [20]:
주야_dummies = pd.get_dummies(df['주야'])
주야_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 주야_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,date,금,목,수,월,일,토,화,야,주
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,토,주,경상,차대차,...,2020-08-22 17:00:00,0,0,0,0,0,1,0,0,1
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,토,주,경상,차대차,...,2020-08-01 09:00:00,0,0,0,0,0,1,0,0,1
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,토,주,경상,차대차,...,2020-09-26 11:00:00,0,0,0,0,0,1,0,0,1
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,토,주,경상,차대차,...,2020-12-12 17:00:00,0,0,0,0,0,1,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,토,주,부상신고,차대차,...,2020-06-27 14:00:00,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,목,야,중상,차대차,...,2018-04-19 00:00:00,0,1,0,0,0,0,0,1,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,목,야,경상,차대차,...,2018-07-19 23:00:00,0,1,0,0,0,0,0,1,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,토,야,경상,차대차,...,2018-01-13 20:00:00,0,0,0,0,0,1,0,1,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,금,야,경상,차대차,...,2017-10-20 18:00:00,1,0,0,0,0,0,0,1,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,수,야,경상,차대차,...,2017-09-13 18:00:00,0,0,1,0,0,0,0,1,0

In [21]:
df.drop(['요일', '주야'], axis = 1, inplace = True)

In [22]:
#사고내용 - 뒤에 동일 컬럼 존재하므로 제거
df['사고내용'].unique()

array(['경상', '부상신고', '중상', '사망'], dtype=object)

In [23]:
df.drop(['사고내용'], axis = 1, inplace = True)

In [24]:
#사고유형_대분류, 사고유형_중분류 -> 사고 유형 컬럼으로
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '기타'), '사고유형_중분류'] = '차대사람_기타'
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '길가장자리구역통행중'), '사고유형_중분류'] = '차대사람_길가장자리구역통행중'
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '보도통행중'), '사고유형_중분류'] = '차대사람_보도통행중'
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '차도통행중	'), '사고유형_중분류'] = '차대사람_차도통행중'
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '횡단중'), '사고유형_중분류'] = '차대사람_횡단중'

df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '기타'), '사고유형_중분류'] = '차대차_기타'
df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '정면충돌'), '사고유형_중분류'] = '차대차_정면충돌'
df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '추돌'), '사고유형_중분류'] = '차대차_추돌'
df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '측면충돌'), '사고유형_중분류'] = '차대차_측면충돌'
df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '후진중충돌'), '사고유형_중분류'] = '차대차_후진중충돌'

df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '공작물충돌'), '사고유형_중분류'] = '차량단독_공작물충돌'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '기타'), '사고유형_중분류'] = '차량단독_기타'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '도로이탈'), '사고유형_중분류'] = '차량단독_도로이탈'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '전도'), '사고유형_중분류'] = '차량단독_전도'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '전도전복'), '사고유형_중분류'] = '차량단독_전도전복'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '전복'), '사고유형_중분류'] = '차량단독_전복'

사고유형_dummies = pd.get_dummies(df['사고유형_중분류'])
사고유형_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 사고유형_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,사고유형_대분류,사고유형_중분류,사고유형,성별가해자,...,차대차_추돌,차대차_측면충돌,차대차_후진중충돌,차도통행중,차량단독_공작물충돌,차량단독_기타,차량단독_도로이탈,차량단독_전도,차량단독_전도전복,차량단독_전복
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,차대차,차대차_기타,기타,기타불명,...,0,0,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,차대차,차대차_기타,기타,남,...,0,0,0,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,차대차,차대차_기타,기타,남,...,0,0,0,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,차대차,차대차_기타,기타,남,...,0,0,0,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,차대차,차대차_측면충돌,측면충돌,남,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,차대차,차대차_측면충돌,측면충돌,남,...,0,1,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,차대차,차대차_기타,기타,여,...,0,0,0,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,차대차,차대차_기타,기타,남,...,0,0,0,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,차대차,차대차_측면충돌,측면충돌,여,...,0,1,0,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,차대차,차대차_기타,기타,남,...,0,0,0,0,0,0,0,0,0,0

In [25]:
df.drop(['사고유형_대분류','사고유형_중분류', '사고유형'], axis = 1, inplace = True)

In [26]:
df['성별가해자'].unique()

array(['기타불명', '남', '여'], dtype=object)

In [27]:
df.loc[(df['성별가해자'] == '남'), '성별가해자'] = '가해자_성별_남'
df.loc[(df['성별가해자'] == '여'), '성별가해자'] = '가해자_성별_여'
df.loc[(df['성별가해자'] == '기타불명'), '성별가해자'] = '가해자_성별_기타불명'

In [28]:
성별가해자_dummies = pd.get_dummies(df['성별가해자'])
성별가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 성별가해자_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,성별가해자,성별가해자_1,연령가해자,연령피해자,...,차도통행중,차량단독_공작물충돌,차량단독_기타,차량단독_도로이탈,차량단독_전도,차량단독_전도전복,차량단독_전복,가해자_성별_기타불명,가해자_성별_남,가해자_성별_여
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,가해자_성별_기타불명,남,불명,74세,...,0,0,0,0,0,0,0,1,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,가해자_성별_남,남,23세,33세,...,0,0,0,0,0,0,0,0,1,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,가해자_성별_남,여,71세,9세,...,0,0,0,0,0,0,0,0,1,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,가해자_성별_남,남,59세,30세,...,0,0,0,0,0,0,0,0,1,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,가해자_성별_남,여,59세,12세,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,가해자_성별_남,남,58세,20세,...,0,0,0,0,0,0,0,0,1,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,가해자_성별_여,남,61세,32세,...,0,0,0,0,0,0,0,0,0,1
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,가해자_성별_남,남,45세,41세,...,0,0,0,0,0,0,0,0,1,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,가해자_성별_여,남,45세,30세,...,0,0,0,0,0,0,0,0,0,1
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,가해자_성별_남,남,26세,33세,...,0,0,0,0,0,0,0,0,1,0

In [29]:
df.drop('성별가해자', axis = 1, inplace = True)

* 추후에 '가해자_성별_기타불명' 컬럼 삭제해야 할 것으로 판단됌.

In [30]:
df['성별가해자_1'].unique()

array(['남', '여', '기타불명', '없음'], dtype=object)

* 기타불명, 없음 : '기타불명'으로 통일함

In [31]:
#피해자성별
df.loc[(df['성별가해자_1'] == '남'), '성별가해자_1'] = '피해자_성별_남'
df.loc[(df['성별가해자_1'] == '여'), '성별가해자_1'] = '피해자_성별_여'
df.loc[(df['성별가해자_1'] == '기타불명'), '성별가해자_1'] = '피해자_성별_기타불명'
df.loc[(df['성별가해자_1'] == '없음'), '성별가해자_1'] = '피해자_성별_기타불명'

In [32]:
성별피해자_dummies = pd.get_dummies(df['성별가해자_1'])
성별피해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 성별피해자_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,성별가해자_1,연령가해자,연령피해자,음주측정수치가해자_대분류,...,차량단독_도로이탈,차량단독_전도,차량단독_전도전복,차량단독_전복,가해자_성별_기타불명,가해자_성별_남,가해자_성별_여,피해자_성별_기타불명,피해자_성별_남,피해자_성별_여
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,피해자_성별_남,불명,74세,기타불명,...,0,0,0,0,1,0,0,0,1,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,피해자_성별_남,23세,33세,해당 없음,...,0,0,0,0,0,1,0,0,1,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,피해자_성별_여,71세,9세,해당 없음,...,0,0,0,0,0,1,0,0,0,1
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,피해자_성별_남,59세,30세,해당 없음,...,0,0,0,0,0,1,0,0,1,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,피해자_성별_여,59세,12세,해당 없음,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,피해자_성별_남,58세,20세,기타불명,...,0,0,0,0,0,1,0,0,1,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,피해자_성별_남,61세,32세,기타불명,...,0,0,0,0,0,0,1,0,1,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,피해자_성별_남,45세,41세,음주상태,...,0,0,0,0,0,1,0,0,1,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,피해자_성별_남,45세,30세,해당 없음,...,0,0,0,0,0,0,1,0,1,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,피해자_성별_남,26세,33세,해당 없음,...,0,0,0,0,0,1,0,0,1,0

In [33]:
df.drop('성별가해자_1', axis = 1, inplace = True) #성별가해자_1(피해자 성별) 컬럼 제거

In [34]:
#연령변수 -> 범주화하여 전처리
# 10대이하, 20, 30, 40, 50, 60, 70, 80, 90대이상

In [35]:
df['연령가해자'].unique()

array(['불명', '23세', '71세', '59세', '54세', '33세', '37세', '75세', '26세',
       '31세', '35세', '51세', '56세', '40세', '65세', '52세', '38세', '68세',
       '28세', '61세', '81세', '36세', '27세', '29세', '44세', '60세', '57세',
       '72세', '58세', '49세', '48세', '66세', '20세', '55세', '39세', '53세',
       '63세', '82세', '41세', '62세', '42세', '45세', '47세', '46세', '24세',
       '32세', '50세', '25세', '80세', '22세', '43세', '77세', '30세', '64세',
       '73세', '21세', '8세', '74세', '76세', '85세', '78세', '67세', '34세',
       '69세', '12세', '19세', '18세', '16세', '99세', '70세', '83세', '14세',
       '13세', '15세', '17세', '79세', '10세', '11세', '6세', '91세', '98세',
       '89세', '9세', '86세', '87세', '84세', '7세', '88세'], dtype=object)

In [36]:
age_gaheaja = []
for i in range(len(df['연령가해자'])):
    a = df['연령가해자'][i].split('세')[0]
    age_gaheaja.append(a)
df['age_gaheaja'] = age_gaheaja

In [37]:
df['age_gaheaja'].unique()

array(['불명', '23', '71', '59', '54', '33', '37', '75', '26', '31', '35',
       '51', '56', '40', '65', '52', '38', '68', '28', '61', '81', '36',
       '27', '29', '44', '60', '57', '72', '58', '49', '48', '66', '20',
       '55', '39', '53', '63', '82', '41', '62', '42', '45', '47', '46',
       '24', '32', '50', '25', '80', '22', '43', '77', '30', '64', '73',
       '21', '8', '74', '76', '85', '78', '67', '34', '69', '12', '19',
       '18', '16', '99', '70', '83', '14', '13', '15', '17', '79', '10',
       '11', '6', '91', '98', '89', '9', '86', '87', '84', '7', '88'],
      dtype=object)

In [38]:
df.loc[(df['age_gaheaja'] == '불명'),'age_gaheaja'] = 100

In [39]:
df['age_gaheaja'].unique()

array([100, '23', '71', '59', '54', '33', '37', '75', '26', '31', '35',
       '51', '56', '40', '65', '52', '38', '68', '28', '61', '81', '36',
       '27', '29', '44', '60', '57', '72', '58', '49', '48', '66', '20',
       '55', '39', '53', '63', '82', '41', '62', '42', '45', '47', '46',
       '24', '32', '50', '25', '80', '22', '43', '77', '30', '64', '73',
       '21', '8', '74', '76', '85', '78', '67', '34', '69', '12', '19',
       '18', '16', '99', '70', '83', '14', '13', '15', '17', '79', '10',
       '11', '6', '91', '98', '89', '9', '86', '87', '84', '7', '88'],
      dtype=object)

In [40]:
df['age_gaheaja'] = df['age_gaheaja'].astype('int')

In [41]:
df['age_gaheaja'].unique()

array([100,  23,  71,  59,  54,  33,  37,  75,  26,  31,  35,  51,  56,
        40,  65,  52,  38,  68,  28,  61,  81,  36,  27,  29,  44,  60,
        57,  72,  58,  49,  48,  66,  20,  55,  39,  53,  63,  82,  41,
        62,  42,  45,  47,  46,  24,  32,  50,  25,  80,  22,  43,  77,
        30,  64,  73,  21,   8,  74,  76,  85,  78,  67,  34,  69,  12,
        19,  18,  16,  99,  70,  83,  14,  13,  15,  17,  79,  10,  11,
         6,  91,  98,  89,   9,  86,  87,  84,   7,  88])

In [42]:
df.loc[(df['age_gaheaja'] < 10), 'age_gaheaja'] = 0
df.loc[(df['age_gaheaja'] >= 10) & (df['age_gaheaja'] < 20), 'age_gaheaja'] = 10
df.loc[(df['age_gaheaja'] >= 20) & (df['age_gaheaja'] < 30), 'age_gaheaja'] = 20
df.loc[(df['age_gaheaja'] >= 30) & (df['age_gaheaja'] < 40), 'age_gaheaja'] = 30
df.loc[(df['age_gaheaja'] >= 40) & (df['age_gaheaja'] < 50), 'age_gaheaja'] = 40
df.loc[(df['age_gaheaja'] >= 50) & (df['age_gaheaja'] < 60), 'age_gaheaja'] = 50
df.loc[(df['age_gaheaja'] >= 60) & (df['age_gaheaja'] < 70), 'age_gaheaja'] = 60
df.loc[(df['age_gaheaja'] >= 70) & (df['age_gaheaja'] < 80), 'age_gaheaja'] = 70
df.loc[(df['age_gaheaja'] >= 80) & (df['age_gaheaja'] < 90), 'age_gaheaja'] = 80
df.loc[(df['age_gaheaja'] >= 90) & (df['age_gaheaja'] < 100), 'age_gaheaja'] = 90

In [43]:
df['age_gaheaja'] = df['age_gaheaja'].astype('str')
df['age_gaheaja'] = df['age_gaheaja'] + '대'

In [44]:
df['age_gaheaja'].unique()

array(['100대', '20대', '70대', '50대', '30대', '40대', '60대', '80대', '0대',
       '10대', '90대'], dtype=object)

In [45]:
df.loc[df['age_gaheaja'] == '0대','age_gaheaja'] = '가해자_연령_10대미만'
df.loc[df['age_gaheaja'] == '10대','age_gaheaja'] = '가해자_연령_10대'
df.loc[df['age_gaheaja'] == '20대','age_gaheaja'] = '가해자_연령_20대'
df.loc[df['age_gaheaja'] == '30대','age_gaheaja'] = '가해자_연령_30대'
df.loc[df['age_gaheaja'] == '40대','age_gaheaja'] = '가해자_연령_40대'
df.loc[df['age_gaheaja'] == '50대','age_gaheaja'] = '가해자_연령_50대'
df.loc[df['age_gaheaja'] == '60대','age_gaheaja'] = '가해자_연령_60대'
df.loc[df['age_gaheaja'] == '70대','age_gaheaja'] = '가해자_연령_70대'
df.loc[df['age_gaheaja'] == '80대','age_gaheaja'] = '가해자_연령_80대'
df.loc[df['age_gaheaja'] == '90대','age_gaheaja'] = '가해자_연령_90대'
df.loc[df['age_gaheaja'] == '100대','age_gaheaja'] = '가해자_연령_불명'

In [46]:
df['age_gaheaja'].unique()

array(['가해자_연령_불명', '가해자_연령_20대', '가해자_연령_70대', '가해자_연령_50대',
       '가해자_연령_30대', '가해자_연령_40대', '가해자_연령_60대', '가해자_연령_80대',
       '가해자_연령_10대미만', '가해자_연령_10대', '가해자_연령_90대'], dtype=object)

In [47]:
가해자연령_dummies = pd.get_dummies(df['age_gaheaja'])
가해자연령_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 가해자연령_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,연령가해자,연령피해자,음주측정수치가해자_대분류,음주측정수치가해자,...,가해자_연령_10대미만,가해자_연령_20대,가해자_연령_30대,가해자_연령_40대,가해자_연령_50대,가해자_연령_60대,가해자_연령_70대,가해자_연령_80대,가해자_연령_90대,가해자_연령_불명
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,불명,74세,기타불명,기타불명,...,0,0,0,0,0,0,0,0,0,1
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,23세,33세,해당 없음,해당 없음,...,0,1,0,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,71세,9세,해당 없음,해당 없음,...,0,0,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,59세,30세,해당 없음,해당 없음,...,0,0,0,0,1,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,59세,12세,해당 없음,해당 없음,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,58세,20세,기타불명,기타불명,...,0,0,0,0,1,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,61세,32세,기타불명,기타불명,...,0,0,0,0,0,1,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,45세,41세,음주상태,0.03%미만,...,0,0,0,1,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,45세,30세,해당 없음,해당 없음,...,0,0,0,1,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,26세,33세,해당 없음,해당 없음,...,0,1,0,0,0,0,0,0,0,0

In [48]:
df.drop(['연령가해자','age_gaheaja'], axis = 1, inplace = True)

In [49]:
df['연령피해자'].unique()

array(['74세', '33세', '9세', '30세', '12세', '7세', '58세', '80세', '10세', '42세',
       '71세', '48세', '44세', '81세', '38세', '54세', '50세', '63세', '51세',
       '65세', '67세', '13세', '79세', '46세', '72세', '31세', '21세', '85세',
       '34세', '11세', '49세', '24세', '22세', '52세', '36세', '69세', '41세',
       '64세', '8세', '15세', '60세', '29세', '53세', '91세', '70세', '82세',
       '56세', '59세', '20세', '76세', '28세', '16세', '83세', '75세', '62세',
       '68세', '73세', '77세', '39세', '26세', '78세', '19세', '43세', '35세',
       '32세', '61세', '55세', '66세', '17세', '45세', '27세', '23세', '25세',
       '37세', '18세', '89세', '57세', '86세', '14세', '40세', '47세', '6세',
       '88세', '84세', '87세', '98세', '90세', '5세', '불명', '없음'], dtype=object)

* 불명, 없음 : 피해자_연령_불명 으로 통일

In [50]:
# 피해자연령 
# 10대이하, 20, 30, 40, 50, 60, 70, 80, 90대이상
age_piheaja = []
for i in range(len(df['연령피해자'])):
    a = df['연령피해자'][i].split('세')[0]
    age_piheaja.append(a)
df['age_piheaja'] = age_piheaja

In [51]:
df['age_piheaja'].unique()

array(['74', '33', '9', '30', '12', '7', '58', '80', '10', '42', '71',
       '48', '44', '81', '38', '54', '50', '63', '51', '65', '67', '13',
       '79', '46', '72', '31', '21', '85', '34', '11', '49', '24', '22',
       '52', '36', '69', '41', '64', '8', '15', '60', '29', '53', '91',
       '70', '82', '56', '59', '20', '76', '28', '16', '83', '75', '62',
       '68', '73', '77', '39', '26', '78', '19', '43', '35', '32', '61',
       '55', '66', '17', '45', '27', '23', '25', '37', '18', '89', '57',
       '86', '14', '40', '47', '6', '88', '84', '87', '98', '90', '5',
       '불명', '없음'], dtype=object)

In [52]:
df.loc[df['age_piheaja'] == '불명', 'age_piheaja'] = 100
df.loc[df['age_piheaja'] == '없음', 'age_piheaja'] = 100

In [53]:
df['age_piheaja'] = df['age_piheaja'].astype('int')

In [54]:
df['age_piheaja'].unique()

array([ 74,  33,   9,  30,  12,   7,  58,  80,  10,  42,  71,  48,  44,
        81,  38,  54,  50,  63,  51,  65,  67,  13,  79,  46,  72,  31,
        21,  85,  34,  11,  49,  24,  22,  52,  36,  69,  41,  64,   8,
        15,  60,  29,  53,  91,  70,  82,  56,  59,  20,  76,  28,  16,
        83,  75,  62,  68,  73,  77,  39,  26,  78,  19,  43,  35,  32,
        61,  55,  66,  17,  45,  27,  23,  25,  37,  18,  89,  57,  86,
        14,  40,  47,   6,  88,  84,  87,  98,  90,   5, 100])

In [55]:
# 숫자로 된 변수 범주화 
df.loc[(df['age_piheaja'] < 10), 'age_piheaja'] = 0
df.loc[(df['age_piheaja'] >= 10) & (df['age_piheaja'] < 20), 'age_piheaja'] = 10
df.loc[(df['age_piheaja'] >= 20) & (df['age_piheaja'] < 30), 'age_piheaja'] = 20
df.loc[(df['age_piheaja'] >= 30) & (df['age_piheaja'] < 40), 'age_piheaja'] = 30
df.loc[(df['age_piheaja'] >= 40) & (df['age_piheaja'] < 50), 'age_piheaja'] = 40
df.loc[(df['age_piheaja'] >= 50) & (df['age_piheaja'] < 60), 'age_piheaja'] = 50
df.loc[(df['age_piheaja'] >= 60) & (df['age_piheaja'] < 70), 'age_piheaja'] = 60
df.loc[(df['age_piheaja'] >= 70) & (df['age_piheaja'] < 80), 'age_piheaja'] = 70
df.loc[(df['age_piheaja'] >= 80) & (df['age_piheaja'] < 90), 'age_piheaja'] = 80
df.loc[(df['age_piheaja'] >= 90) & (df['age_piheaja'] < 100), 'age_piheaja'] = 90

In [56]:
df['age_piheaja'] = df['age_piheaja'].astype('str')
df['age_piheaja'] = df['age_piheaja'] + '대'

In [57]:
df['age_piheaja'].unique()

array(['70대', '30대', '0대', '10대', '50대', '80대', '40대', '60대', '20대',
       '90대', '100대'], dtype=object)

In [58]:
df.loc[df['age_piheaja'] == '0대','age_piheaja'] = '피해자_연령_10대미만'
df.loc[df['age_piheaja'] == '10대','age_piheaja'] = '피해자_연령_10대'
df.loc[df['age_piheaja'] == '20대','age_piheaja'] = '피해자_연령_20대'
df.loc[df['age_piheaja'] == '30대','age_piheaja'] = '피해자_연령_30대'
df.loc[df['age_piheaja'] == '40대','age_piheaja'] = '피해자_연령_40대'
df.loc[df['age_piheaja'] == '50대','age_piheaja'] = '피해자_연령_50대'
df.loc[df['age_piheaja'] == '60대','age_piheaja'] = '피해자_연령_60대'
df.loc[df['age_piheaja'] == '70대','age_piheaja'] = '피해자_연령_70대'
df.loc[df['age_piheaja'] == '80대','age_piheaja'] = '피해자_연령_80대'
df.loc[df['age_piheaja'] == '90대','age_piheaja'] = '피해자_연령_90대'
df.loc[df['age_piheaja'] == '100대','age_piheaja'] = '피해자_연령_불명'

In [59]:
df['age_piheaja'].unique()

array(['피해자_연령_70대', '피해자_연령_30대', '피해자_연령_10대미만', '피해자_연령_10대',
       '피해자_연령_50대', '피해자_연령_80대', '피해자_연령_40대', '피해자_연령_60대',
       '피해자_연령_20대', '피해자_연령_90대', '피해자_연령_불명'], dtype=object)

In [62]:
피해자연령_dummies = pd.get_dummies(df['age_piheaja'])
피해자연령_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 피해자연령_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,연령피해자,음주측정수치가해자_대분류,음주측정수치가해자,보호장구가해자_대분류,...,피해자_연령_10대미만,피해자_연령_20대,피해자_연령_30대,피해자_연령_40대,피해자_연령_50대,피해자_연령_60대,피해자_연령_70대,피해자_연령_80대,피해자_연령_90대,피해자_연령_불명
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,74세,기타불명,기타불명,기타불명,...,0,0,0,0,0,0,1,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,33세,해당 없음,해당 없음,기타불명,...,0,0,1,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,9세,해당 없음,해당 없음,안전벨트/카시트,...,1,0,0,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,30세,해당 없음,해당 없음,안전벨트/카시트,...,0,0,1,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,12세,해당 없음,해당 없음,안전벨트/카시트,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,20세,기타불명,기타불명,기타불명,...,0,1,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,32세,기타불명,기타불명,안전벨트/카시트,...,0,0,1,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,41세,음주상태,0.03%미만,안전벨트/카시트,...,0,0,0,1,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,30세,해당 없음,해당 없음,안전벨트/카시트,...,0,0,1,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,33세,해당 없음,해당 없음,기타불명,...,0,0,1,0,0,0,0,0,0,0

In [64]:
df.drop(['연령피해자','age_piheaja'], axis = 1, inplace = True)

In [65]:
print(df['음주측정수치가해자_대분류'].unique()) #확실히 음주 상태인 것을 1, 아닌 것을 0으로 mapping
mapping = {'기타불명'  : 0,
           '해당 없음' : 0, 
           '측정불능'  : 0, 
           '음주운전'  : 1,
           '음주상태'  : 1}
df['음주측정수치가해자_대분류'] = df['음주측정수치가해자_대분류'].map(mapping)
df['음주측정수치가해자_대분류']

['기타불명' '해당 없음' '음주운전' '음주상태' '측정불능']

0       0
1       0
2       0
3       0
4       0
       ..
1818    0
1819    0
1820    1
1821    0
1822    0
Name: 음주측정수치가해자_대분류, Length: 1823, dtype: int64

In [68]:
df = df.rename(columns={'음주측정수치가해자_대분류':'가해자_음주_여부'})

In [69]:
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,음주측정수치가해자,보호장구가해자_대분류,보호장구가해자,...,피해자_연령_10대미만,피해자_연령_20대,피해자_연령_30대,피해자_연령_40대,피해자_연령_50대,피해자_연령_60대,피해자_연령_70대,피해자_연령_80대,피해자_연령_90대,피해자_연령_불명
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,기타불명,기타불명,기타불명,...,0,0,0,0,0,0,1,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,해당 없음,기타불명,기타불명,...,0,0,1,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,해당 없음,안전벨트/카시트,착용불명,...,1,0,0,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,해당 없음,안전벨트/카시트,착용,...,0,0,1,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,해당 없음,안전벨트/카시트,착용,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,기타불명,기타불명,기타불명,...,0,1,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,기타불명,안전벨트/카시트,착용,...,0,0,1,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,0.03%미만,안전벨트/카시트,착용,...,0,0,0,1,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,해당 없음,안전벨트/카시트,착용,...,0,0,1,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,해당 없음,기타불명,기타불명,...,0,0,1,0,0,0,0,0,0,0

In [73]:
df.drop('음주측정수치가해자', axis = 1, inplace = True)

In [74]:
df['보호장구가해자_대분류'].unique()

array(['기타불명', '안전벨트/카시트', '안전모'], dtype=object)

In [76]:
df['빈도 수'] = 1

In [77]:
pd.DataFrame(df.groupby(['보호장구가해자_대분류','보호장구가해자'])['빈도 수'].count())

                     빈도 수
보호장구가해자_대분류 보호장구가해자
기타불명        기타불명      350
안전모         미착용       273
            착용        146
            착용불명       59
안전벨트/카시트    미착용        11
            착용        786
            착용불명      198

In [78]:
df.loc[(df['보호장구가해자'] == '기타불명'), '보호장구가해자'] = '가해자_보호장구_기타불명'
df.loc[(df['보호장구가해자_대분류'] == '안전모')&(df['보호장구가해자'] == '미착용'),'보호장구가해자'] = '가해자_안전모_미착용'
df.loc[(df['보호장구가해자_대분류'] == '안전모')&(df['보호장구가해자'] == '착용'), '보호장구가해자'] = '가해자_안전모_착용'
df.loc[(df['보호장구가해자_대분류'] == '안전모')&(df['보호장구가해자'] == '착용불명'),'보호장구가해자'] = '가해자_안전모_착용불명' 
df.loc[(df['보호장구가해자_대분류'] == '안전벨트/카시트')&(df['보호장구가해자'] == '미착용'),'보호장구가해자'] = '가해자_안전벨트/카시트_미착용'
df.loc[(df['보호장구가해자_대분류'] == '안전벨트/카시트')&(df['보호장구가해자'] == '착용'),'보호장구가해자'] = '가해자_안전벨트/카시트_착용'
df.loc[(df['보호장구가해자_대분류'] == '안전벨트/카시트')&(df['보호장구가해자'] == '착용불명'),'보호장구가해자'] = '가해자_안전벨트/카시트_착용불명'

In [79]:
df['보호장구가해자'].unique()

array(['가해자_보호장구_기타불명', '가해자_안전벨트/카시트_착용불명', '가해자_안전벨트/카시트_착용',
       '가해자_안전모_착용', '가해자_안전벨트/카시트_미착용', '가해자_안전모_미착용', '가해자_안전모_착용불명'],
      dtype=object)

In [80]:
보호장구가해자_dummies = pd.get_dummies(df['보호장구가해자'])
보호장구가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 보호장구가해자_dummies, how = 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,보호장구가해자_대분류,보호장구가해자,보호장구피해자_대분류,...,피해자_연령_90대,피해자_연령_불명,빈도 수,가해자_보호장구_기타불명,가해자_안전모_미착용,가해자_안전모_착용,가해자_안전모_착용불명,가해자_안전벨트/카시트_미착용,가해자_안전벨트/카시트_착용,가해자_안전벨트/카시트_착용불명
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,기타불명,가해자_보호장구_기타불명,기타불명,...,0,0,1,1,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,기타불명,가해자_보호장구_기타불명,안전모,...,0,0,1,1,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,안전벨트/카시트,가해자_안전벨트/카시트_착용불명,안전모,...,0,0,1,0,0,0,0,0,0,1
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,안전벨트/카시트,가해자_안전벨트/카시트_착용,안전모,...,0,0,1,0,0,0,0,0,1,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,안전벨트/카시트,가해자_안전벨트/카시트_착용,안전모,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,기타불명,가해자_보호장구_기타불명,기타불명,...,0,0,1,1,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,안전벨트/카시트,가해자_안전벨트/카시트_착용,안전모,...,0,0,1,0,0,0,0,0,1,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,안전벨트/카시트,가해자_안전벨트/카시트_착용,안전모,...,0,0,1,0,0,0,0,0,1,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,안전벨트/카시트,가해자_안전벨트/카시트_착용,안전모,...,0,0,1,0,0,0,0,0,1,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,기타불명,가해자_보호장구_기타불명,안전모,...,0,0,1,1,0,0,0,0,0,0

In [81]:
df.drop(['보호장구가해자_대분류','보호장구가해자'], axis = 1, inplace = True)

In [82]:
df.columns

Index(['index', 'TAAS사고관리번호', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT',
       '가해자_음주_여부', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자',
       ...
       '피해자_연령_90대', '피해자_연령_불명', '빈도 수', '가해자_보호장구_기타불명', '가해자_안전모_미착용',
       '가해자_안전모_착용', '가해자_안전모_착용불명', '가해자_안전벨트/카시트_미착용', '가해자_안전벨트/카시트_착용',
       '가해자_안전벨트/카시트_착용불명'],
      dtype='object', length=107)

In [83]:
df['보호장구피해자'].unique()

array(['기타불명', '미착용', '착용', '착용불명', '보행자', '없음'], dtype=object)

In [84]:
pd.DataFrame(df.groupby(['보호장구피해자_대분류','보호장구피해자'])['빈도 수'].count())

                     빈도 수
보호장구피해자_대분류 보호장구피해자
기타불명        기타불명      323
보행자         보행자        82
안전모         미착용       557
            착용        398
            착용불명      145
안전벨트/카시트    미착용         2
            착용        219
            착용불명       68
없음          없음         29

In [85]:
df.loc[(df['보호장구피해자'] == '기타불명'), '보호장구피해자'] = '피해자_보호장구_기타불명'
df.loc[(df['보호장구피해자'] == '보행자'), '보호장구피해자'] = '피해자_보호장구_보행자'
df.loc[(df['보호장구피해자'] == '없음'), '보호장구피해자'] = '피해자_보호장구_없음'
df.loc[(df['보호장구피해자_대분류'] == '안전모')&(df['보호장구피해자'] == '미착용'),'보호장구피해자'] = '피해자_안전모_미착용'
df.loc[(df['보호장구피해자_대분류'] == '안전모')&(df['보호장구피해자'] == '착용'), '보호장구피해자'] = '피해자_안전모_착용'
df.loc[(df['보호장구피해자_대분류'] == '안전모')&(df['보호장구피해자'] == '착용불명'),'보호장구피해자'] = '피해자_안전모_착용불명' 
df.loc[(df['보호장구피해자_대분류'] == '안전벨트/카시트')&(df['보호장구피해자'] == '미착용'),'보호장구피해자'] = '피해자_안전벨트/카시트_미착용'
df.loc[(df['보호장구피해자_대분류'] == '안전벨트/카시트')&(df['보호장구피해자'] == '착용'),'보호장구피해자'] = '피해자_안전벨트/카시트_착용'
df.loc[(df['보호장구피해자_대분류'] == '안전벨트/카시트')&(df['보호장구피해자'] == '착용불명'),'보호장구피해자'] = '피해자_안전벨트/카시트_착용불명'

In [86]:
보호장구피해자_dummies = pd.get_dummies(df['보호장구피해자'])
보호장구피해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 보호장구피해자_dummies, how = 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,보호장구피해자_대분류,보호장구피해자,법규위반가해자,...,가해자_안전벨트/카시트_착용불명,피해자_보호장구_기타불명,피해자_보호장구_보행자,피해자_보호장구_없음,피해자_안전모_미착용,피해자_안전모_착용,피해자_안전모_착용불명,피해자_안전벨트/카시트_미착용,피해자_안전벨트/카시트_착용,피해자_안전벨트/카시트_착용불명
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,기타불명,피해자_보호장구_기타불명,안전운전 의무 불이행,...,0,1,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,안전모,피해자_안전모_미착용,안전운전 의무 불이행,...,0,0,0,0,1,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,안전모,피해자_안전모_착용,안전운전 의무 불이행,...,1,0,0,0,0,1,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,안전모,피해자_안전모_미착용,안전운전 의무 불이행,...,0,0,0,0,1,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,안전모,피해자_안전모_미착용,안전운전 의무 불이행,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,기타불명,피해자_보호장구_기타불명,안전거리 미확보,...,0,1,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,안전모,피해자_안전모_미착용,안전운전 의무 불이행,...,0,0,0,0,1,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,안전모,피해자_안전모_미착용,안전운전 의무 불이행,...,0,0,0,0,1,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,안전모,피해자_안전모_미착용,안전운전 의무 불이행,...,0,0,0,0,1,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,안전모,피해자_안전모_미착용,신호위반,...,0,0,0,0,1,0,0,0,0,0

In [87]:
df.drop(['보호장구피해자_대분류','보호장구피해자'], axis = 1,inplace = True)

In [88]:
df['법규위반가해자'].unique()

array(['안전운전 의무 불이행', '신호위반', '교차로 통행방법 위반', '기타', '안전거리 미확보', '중앙선 침범',
       '과속', '보행자 보호의무 위반'], dtype=object)

In [89]:
#법규위반가해자 : 더미 변수 생성 (법가 + 세부항목) 후 컬럼 제거
df['법규위반가해자'] = '법가' + '_' + df['법규위반가해자']
법규위반가해자_dummies = pd.get_dummies(df['법규위반가해자'])
법규위반가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 법규위반가해자_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,법규위반가해자,행동유형가해자_대분류,행동유형가해자_중분류,...,피해자_안전벨트/카시트_착용,피해자_안전벨트/카시트_착용불명,법가_과속,법가_교차로 통행방법 위반,법가_기타,법가_보행자 보호의무 위반,법가_신호위반,법가_안전거리 미확보,법가_안전운전 의무 불이행,법가_중앙선 침범
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,법가_안전운전 의무 불이행,불명,불명,...,0,0,0,0,0,0,0,0,1,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,법가_안전운전 의무 불이행,운전자,회전관련,...,0,0,0,0,0,0,0,0,1,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,법가_안전운전 의무 불이행,운전자,직진관련,...,0,0,0,0,0,0,0,0,1,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,법가_안전운전 의무 불이행,운전자,회전관련,...,0,0,0,0,0,0,0,0,1,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,법가_안전운전 의무 불이행,운전자,직진관련,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,법가_안전거리 미확보,운전자,회전관련,...,0,0,0,0,0,0,0,1,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,법가_안전운전 의무 불이행,운전자,주행 중 대기,...,0,0,0,0,0,0,0,0,1,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,법가_안전운전 의무 불이행,운전자,회전관련,...,0,0,0,0,0,0,0,0,1,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,법가_안전운전 의무 불이행,운전자,회전관련,...,0,0,0,0,0,0,0,0,1,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,법가_신호위반,운전자,회전관련,...,0,0,0,0,0,0,1,0,0,0

In [90]:
df.drop('법규위반가해자', axis = 1, inplace = True) #법규위반가해자 컬럼 제거

* 행동유형가해자_대분류, 행동유형가해자_중분류, 행동유형가해자 에서 '행동유형가해자' 만 살리기로 함

In [91]:
df['행동유형가해자_대분류'].unique()

array(['불명', '운전자'], dtype=object)

In [92]:
df['행동유형가해자_중분류'].unique()

array(['불명', '회전관련', '직진관련', '주정차중', '후진 중', '기타', '자동차 등', '주행 중 대기'],
      dtype=object)

In [93]:
df['행동유형가해자'].unique()

array(['불명', '우회전 중', '직진 중', '좌회전 중', '진로변경 중', '앞지르기 중', '주정차중', '후진 중',
       '기타', '좌우회전중', 'U턴 중', '직진중', 'U턴중', '후진중', '주ㆍ정차중 ', '진로변경중',
       '앞지르기중', '주행 중 대기', '출발중'], dtype=object)

In [94]:
pd.DataFrame(df['행동유형가해자'].value_counts())

         행동유형가해자
직진 중         716
우회전 중        256
좌회전 중        188
직진중          167
좌우회전중        152
기타            99
진로변경 중        57
불명            44
후진 중          28
진로변경중         23
U턴 중          21
주정차중          15
U턴중           13
앞지르기 중        11
후진중           10
주ㆍ정차중          9
주행 중 대기        7
출발중            4
앞지르기중          3

In [95]:
df.loc[(df['행동유형가해자'] == '직진 중'), '행동유형가해자'] = '가해자_행동_직진중'
df.loc[(df['행동유형가해자'] == '우회전 중'), '행동유형가해자'] = '가해자_행동_우회전중'
df.loc[(df['행동유형가해자'] == '좌회전 중'), '행동유형가해자'] = '가해자_행동_좌회전중'
df.loc[(df['행동유형가해자'] == '직진중'), '행동유형가해자'] = '가해자_행동_직진중'
df.loc[(df['행동유형가해자'] == '좌우회전중'), '행동유형가해자'] = '가해자_행동_좌우회전중'
df.loc[(df['행동유형가해자'] == '기타'), '행동유형가해자'] = '가해자_행동_기타'
df.loc[(df['행동유형가해자'] == '진로변경 중'), '행동유형가해자'] = '가해자_행동_진로변경중'
df.loc[(df['행동유형가해자'] == '불명'), '행동유형가해자'] = '가해자_행동_불명'
df.loc[(df['행동유형가해자'] == '후진 중'), '행동유형가해자'] = '가해자_행동_후진중'
df.loc[(df['행동유형가해자'] == '진로변경중'), '행동유형가해자'] = '가해자_행동_진로변경중'
df.loc[(df['행동유형가해자'] == 'U턴 중'), '행동유형가해자'] = '가해자_행동_U턴중'
df.loc[(df['행동유형가해자'] == '주정차중'), '행동유형가해자'] = '가해자_행동_주정차중'
df.loc[(df['행동유형가해자'] == 'U턴중'), '행동유형가해자'] ='가해자_행동_U턴중'
df.loc[(df['행동유형가해자'] == '앞지르기 중'), '행동유형가해자'] = '가해자_행동_앞지르기중'
df.loc[(df['행동유형가해자'] == '후진중'), '행동유형가해자'] ='가해자_행동_후진중'
df.loc[(df['행동유형가해자'] == '주ㆍ정차중 '), '행동유형가해자'] = '가해자_행동_주정차중'
df.loc[(df['행동유형가해자'] == '주행 중 대기'), '행동유형가해자'] = '가해자_행동_주행중대기'
df.loc[(df['행동유형가해자'] == '출발중'), '행동유형가해자'] = '가해자_행동_출발중'
df.loc[(df['행동유형가해자'] == '앞지르기중'), '행동유형가해자'] = '가해자_행동_앞지르기중'

In [96]:
행동유형가해자_dummies = pd.get_dummies(df['행동유형가해자'])
행동유형가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 행동유형가해자_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,행동유형가해자_대분류,행동유형가해자_중분류,행동유형가해자,...,가해자_행동_앞지르기중,가해자_행동_우회전중,가해자_행동_좌우회전중,가해자_행동_좌회전중,가해자_행동_주정차중,가해자_행동_주행중대기,가해자_행동_직진중,가해자_행동_진로변경중,가해자_행동_출발중,가해자_행동_후진중
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,불명,불명,가해자_행동_불명,...,0,0,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,운전자,회전관련,가해자_행동_우회전중,...,0,1,0,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,운전자,직진관련,가해자_행동_직진중,...,0,0,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,운전자,회전관련,가해자_행동_우회전중,...,0,1,0,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,운전자,직진관련,가해자_행동_직진중,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,운전자,회전관련,가해자_행동_U턴중,...,0,0,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,운전자,주행 중 대기,가해자_행동_주행중대기,...,0,0,0,0,0,1,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,운전자,회전관련,가해자_행동_U턴중,...,0,0,0,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,운전자,회전관련,가해자_행동_우회전중,...,0,1,0,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,운전자,회전관련,가해자_행동_좌우회전중,...,0,0,1,0,0,0,0,0,0,0

In [97]:
df.drop(['행동유형가해자_대분류','행동유형가해자_중분류','행동유형가해자'], axis = 1, inplace = True)

* 신체상해정도가해자, 신체상해정도피해자 : 생략 / 이전 전처리때 생략하였음 (컬럼 삭제)

In [98]:
df['신체상해정도가해자'].unique()

array(['기타불명', '상해없음', '경상', '부상신고', '중상', '사망'], dtype=object)

In [99]:
df['신체상해정도피해자'].unique()

array(['경상', '부상신고', '중상', '상해없음', '사망', '기타불명', '없음'], dtype=object)

In [100]:
df.drop(['신체상해정도가해자','신체상해정도피해자'], axis = 1, inplace = True)

In [101]:
df['가해자신체상해주부위'].unique()

array(['상해없음', '손', '앞목', '기타', '뒷목', '허리', '얼굴', '팔', '발', '가슴', '어깨',
       '하퇴부', '목', '머리', '대퇴부', '배', '불명'], dtype=object)

In [102]:
df['피해자신체상해주부위'].unique()

array(['하퇴부', '팔', '허리', '기타', '상해없음', '머리', '발', '대퇴부', '가슴', '손', '얼굴',
       '뒷목', '어깨', '배', '목', '불명', '앞목', '등', '없음'], dtype=object)

In [103]:
#가해자신체상해주부위, 피해자신체상해주부위 : 더미변수 생성 (가 + 신체부위 컬럼) 후 컬럼 제거
df['가해자신체상해주부위'] = '가' + '_' + df['가해자신체상해주부위'] 
df_가해자신체상해주부위_dummies = pd.get_dummies(data = df['가해자신체상해주부위'])
df_가해자신체상해주부위_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호'] 
df = pd.merge(df, df_가해자신체상해주부위_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,가해자신체상해주부위,피해자신체상해주부위,당사자종별가해자_대분류,...,가_배,가_불명,가_상해없음,가_손,가_앞목,가_어깨,가_얼굴,가_팔,가_하퇴부,가_허리
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,가_상해없음,하퇴부,불명,...,0,0,1,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,가_상해없음,팔,승용차,...,0,0,1,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,가_상해없음,허리,승용차,...,0,0,1,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,가_상해없음,기타,화물차,...,0,0,1,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,가_상해없음,하퇴부,승용차,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,가_상해없음,기타,승용차,...,0,0,1,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,가_상해없음,손,승용차,...,0,0,1,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,가_상해없음,어깨,화물차,...,0,0,1,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,가_상해없음,허리,승용차,...,0,0,1,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,가_상해없음,기타,승용차,...,0,0,1,0,0,0,0,0,0,0

In [104]:
df.drop('가해자신체상해주부위', axis = 1, inplace = True)

In [105]:
df['피해자신체상해주부위'] = '피' + '_' + df['피해자신체상해주부위']
df_피해자신체상해주부위_dummies = pd.get_dummies(data = df['피해자신체상해주부위'])
df_피해자신체상해주부위_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_피해자신체상해주부위_dummies, how= 'outer', on = 'TAAS사고관리번호')

In [106]:
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,피해자신체상해주부위,당사자종별가해자_대분류,당사자종별가해자,...,피_불명,피_상해없음,피_손,피_앞목,피_어깨,피_얼굴,피_없음,피_팔,피_하퇴부,피_허리
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,피_하퇴부,불명,불명,...,0,0,0,0,0,0,0,0,1,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,피_팔,승용차,승용차,...,0,0,0,0,0,0,0,1,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,피_허리,승용차,승용차,...,0,0,0,0,0,0,0,0,0,1
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,피_기타,화물차,화물차,...,0,0,0,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,피_하퇴부,승용차,승용차,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,피_기타,승용차,승용차,...,0,0,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,피_손,승용차,승용차,...,0,0,1,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,피_어깨,화물차,화물차,...,0,0,0,0,1,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,피_허리,승용차,승용차,...,0,0,0,0,0,0,0,0,0,1
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,피_기타,승용차,승용차,...,0,0,0,0,0,0,0,0,0,0

In [107]:
df.drop('피해자신체상해주부위', axis = 1, inplace = True)

* 당사자종별가해자_대분류 컬럼의 속성을 살려서, 더미변수화

In [108]:
#당사자종별가해자_대분류
df['당사자종별가해자_대분류'].unique()

array(['불명', '승용차', '화물차', '자전거', '원동기장치자전거', '승합차', '이륜차', '건설기계', '특수차',
       '사륜오토바이(ATV)', '개인형이동수단(PM)', '기타'], dtype=object)

In [109]:
pd.DataFrame(df.groupby(['당사자종별가해자_대분류','당사자종별가해자'])['빈도 수'].count())

                          빈도 수
당사자종별가해자_대분류 당사자종별가해자
개인형이동수단(PM)  개인형이동수단(PM)    46
건설기계         건설기계           10
기타           기타              1
불명           불명             36
사륜오토바이(ATV)  사륜오토바이(ATV)     2
승용차          경형             97
             대형              3
             소형             21
             승용차           739
             중형             94
승합차          경형              4
             대형              2
             소형              5
             승합차            45
             중형              2
원동기장치자전거     원동기장치자전거       20
이륜차          소형             12
             이륜차            39
자전거          자전거           486
특수차          특수차             4
화물차          경형              1
             대형              1
             소형             24
             중형              1
             화물차           128

In [110]:
df['당사자종별가해자_대분류'] = '당종가' + '_' + df['당사자종별가해자_대분류']
df_당사자종별가해자_dummies = pd.get_dummies(data = df['당사자종별가해자_대분류'])
df_당사자종별가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_당사자종별가해자_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,당사자종별가해자_대분류,당사자종별가해자,당사자종별피해자_대분류,...,당종가_기타,당종가_불명,당종가_사륜오토바이(ATV),당종가_승용차,당종가_승합차,당종가_원동기장치자전거,당종가_이륜차,당종가_자전거,당종가_특수차,당종가_화물차
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,당종가_불명,불명,자전거,...,0,1,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,당종가_승용차,승용차,자전거,...,0,0,0,1,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,당종가_승용차,승용차,자전거,...,0,0,0,1,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,당종가_화물차,화물차,자전거,...,0,0,0,0,0,0,0,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,당종가_승용차,승용차,자전거,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,당종가_승용차,승용차,개인형이동수단(PM),...,0,0,0,1,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,당종가_승용차,승용차,개인형이동수단(PM),...,0,0,0,1,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,당종가_화물차,화물차,개인형이동수단(PM),...,0,0,0,0,0,0,0,0,0,1
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,당종가_승용차,승용차,개인형이동수단(PM),...,0,0,0,1,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,당종가_승용차,승용차,개인형이동수단(PM),...,0,0,0,1,0,0,0,0,0,0

In [111]:
df.drop('당사자종별가해자', axis  = 1, inplace = True)

In [112]:
df.drop('당사자종별가해자_대분류', axis = 1, inplace = True)

* 당사자종별피해자_대분류 컬럼의 속성을 살려서, 더미변수화

In [113]:
pd.DataFrame(df.groupby(['당사자종별피해자_대분류','당사자종별피해자'])['빈도 수'].count())

                          빈도 수
당사자종별피해자_대분류 당사자종별피해자
개인형이동수단(PM)  개인형이동수단(PM)    50
건설기계         건설기계            2
보행자          보행자            82
불명           불명              6
승용차          경형             30
             대형              1
             소형              2
             승용차           227
             중형             25
승합차          대형              1
             소형              2
             승합차            18
             중형              1
없음           없음             29
원동기장치자전거     원동기장치자전거      311
이륜차          소형              5
             이륜차            19
자전거          자전거           975
특수차          경형              2
             특수차             2
화물차          소형              4
             화물차            29

In [114]:
len(df['당사자종별피해자_대분류'].unique())

12

In [115]:
df['당사자종별피해자_대분류'] = '당종피' + '_' + df['당사자종별피해자_대분류']
df_당사자종별피해자_dummies = pd.get_dummies(data = df['당사자종별피해자_대분류'])
df_당사자종별피해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_당사자종별피해자_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,당사자종별피해자_대분류,당사자종별피해자,차량용도가해자_대분류,...,당종피_보행자,당종피_불명,당종피_승용차,당종피_승합차,당종피_없음,당종피_원동기장치자전거,당종피_이륜차,당종피_자전거,당종피_특수차,당종피_화물차
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,당종피_자전거,자전거,불명,...,0,0,0,0,0,0,0,1,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,당종피_자전거,자전거,비사업용,...,0,0,0,0,0,0,0,1,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,당종피_자전거,자전거,사업용,...,0,0,0,0,0,0,0,1,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,당종피_자전거,자전거,비사업용,...,0,0,0,0,0,0,0,1,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,당종피_자전거,자전거,비사업용,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,당종피_개인형이동수단(PM),개인형이동수단(PM),사업용,...,0,0,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,당종피_개인형이동수단(PM),개인형이동수단(PM),사업용,...,0,0,0,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,당종피_개인형이동수단(PM),개인형이동수단(PM),비사업용,...,0,0,0,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,당종피_개인형이동수단(PM),개인형이동수단(PM),비사업용,...,0,0,0,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,당종피_개인형이동수단(PM),개인형이동수단(PM),비사업용,...,0,0,0,0,0,0,0,0,0,0

In [116]:
df.drop(['당사자종별피해자','당사자종별피해자_대분류'], axis = 1, inplace = True)

* 차량용도가해자_대분류, 차량용도가해자_중분류, 차량용도가해자 -  중분류 속성만 살려서 더미변수화
* 사업용/비사업용 구분 없이 묶어버리기 - 결론 : 중분류만 살려서 더미변수화
* 버스종류는 버스로 묶기

In [117]:
pd.DataFrame(df.groupby(['차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자'])['빈도 수'].count())

                                     빈도 수
차량용도가해자_대분류 차량용도가해자_중분류 차량용도가해자
개인형이동수단(PM) 개인형이동수단(PM) 개인형이동수단(PM)    46
기타          기타          기타              1
기타불명        기타불명        기타/불명          11
불명          불명          불명             25
비사업용        기타/건설기계     기타/건설기계        10
            버스          버스             19
            비사업용기타      비사업용기타          7
            승용차         승용차           780
            어린이통학버스     어린이통학버스         7
            화물차         화물차           131
사륜오토바이(ATV) 사륜오토바이(ATV) 사륜오토바이(ATV)     2
사업용         기타/건설기계     기타/건설기계        12
            노선버스        고속버스            1
                        시내버스            8
            렌터카         렌터카            42
            전세버스        전세버스            5
            택시          개인택시           38
                        법인택시           94
            화물차         일반화물            3
                        화물차            24
원동기장치자전거    원동기장치자전거    원동기장치자전거       20
이륜차         이륜차         이륜차            51
자전거         자전거         자전거           486

In [118]:
df['차량용도가해자_중분류'].unique()

array(['불명', '승용차', '렌터카', '화물차', '자전거', '원동기장치자전거', '택시', '버스', '이륜차',
       '기타/건설기계', '기타불명', '노선버스', '전세버스', '비사업용기타', '어린이통학버스',
       '사륜오토바이(ATV)', '개인형이동수단(PM)', '기타'], dtype=object)

* 버스 : 버스, 노선버스, 전세버스
* 기타 : 불명, 기타/건설기계, 기타불명, 비사업용기타, 기타
* 자전거 : 원동기장치자전거, 자전거

In [119]:
df.loc[(df['차량용도가해자_중분류'] == '불명'), '차량용도가해자'] = '가해자_차량용도_불명'
df.loc[(df['차량용도가해자_중분류'] == '승용차'), '차량용도가해자'] = '가해자_차량용도_승용차'
df.loc[(df['차량용도가해자_중분류'] == '렌터카'), '차량용도가해자'] = '가해자_차량용도_렌터카'
df.loc[(df['차량용도가해자_중분류'] == '화물차'), '차량용도가해자'] = '가해자_차량용도_화물차'
df.loc[(df['차량용도가해자_중분류'] == '자전거'), '차량용도가해자'] = '가해자_차량용도_자전거'
df.loc[(df['차량용도가해자_중분류'] == '원동기장치자전거'), '차량용도가해자'] = '가해자_차량용도_자전거'
df.loc[(df['차량용도가해자_중분류'] == '택시'), '차량용도가해자'] = '가해자_차량용도_택시'
df.loc[(df['차량용도가해자_중분류'] == '버스'), '차량용도가해자'] = '가해자_차량용도_버스'
df.loc[(df['차량용도가해자_중분류'] == '이륜차'), '차량용도가해자'] = '가해자_차량용도_이륜차'
df.loc[(df['차량용도가해자_중분류'] == '기타/건설기계'), '차량용도가해자'] = '가해자_차량용도_기타'
df.loc[(df['차량용도가해자_중분류'] == '기타불명'), '차량용도가해자'] = '가해자_차량용도_기타'
df.loc[(df['차량용도가해자_중분류'] == '노선버스'), '차량용도가해자'] = '가해자_차량용도_버스'
df.loc[(df['차량용도가해자_중분류'] == '전세버스'), '차량용도가해자'] = '가해자_차량용도_버스'
df.loc[(df['차량용도가해자_중분류'] == '비사업용기타'), '차량용도가해자'] = '가해자_차량용도_기타'
df.loc[(df['차량용도가해자_중분류'] == '어린이통학버스'), '차량용도가해자'] = '가해자_차량용도_버스'
df.loc[(df['차량용도가해자_중분류'] == '사륜오토바이(ATV)'), '차량용도가해자'] = '가해자_차량용도_사륜오토바이'
df.loc[(df['차량용도가해자_중분류'] == '개인형이동수단(PM)'), '차량용도가해자'] = '가해자_차량용도_PM'
df.loc[(df['차량용도가해자_중분류'] == '기타'), '차량용도가해자'] = '가해자_차량용도_기타'

In [120]:
df['차량용도가해자'].unique()

array(['가해자_차량용도_불명', '가해자_차량용도_승용차', '가해자_차량용도_렌터카', '가해자_차량용도_화물차',
       '가해자_차량용도_자전거', '가해자_차량용도_택시', '가해자_차량용도_버스', '가해자_차량용도_이륜차',
       '가해자_차량용도_기타', '가해자_차량용도_사륜오토바이', '가해자_차량용도_PM'], dtype=object)

In [121]:
df_차량용도가해자_dummies = pd.get_dummies(data = df['차량용도가해자'])
df_차량용도가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_차량용도가해자_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,차량용도가해자_대분류,차량용도가해자_중분류,차량용도가해자,...,가해자_차량용도_기타,가해자_차량용도_렌터카,가해자_차량용도_버스,가해자_차량용도_불명,가해자_차량용도_사륜오토바이,가해자_차량용도_승용차,가해자_차량용도_이륜차,가해자_차량용도_자전거,가해자_차량용도_택시,가해자_차량용도_화물차
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,불명,불명,가해자_차량용도_불명,...,0,0,0,1,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,비사업용,승용차,가해자_차량용도_승용차,...,0,0,0,0,0,1,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,사업용,렌터카,가해자_차량용도_렌터카,...,0,1,0,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,비사업용,화물차,가해자_차량용도_화물차,...,0,0,0,0,0,0,0,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,비사업용,승용차,가해자_차량용도_승용차,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,사업용,택시,가해자_차량용도_택시,...,0,0,0,0,0,0,0,0,1,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,사업용,택시,가해자_차량용도_택시,...,0,0,0,0,0,0,0,0,1,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,비사업용,화물차,가해자_차량용도_화물차,...,0,0,0,0,0,0,0,0,0,1
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,비사업용,승용차,가해자_차량용도_승용차,...,0,0,0,0,0,1,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,비사업용,승용차,가해자_차량용도_승용차,...,0,0,0,0,0,1,0,0,0,0

In [122]:
df.drop(['차량용도가해자_대분류','차량용도가해자_중분류','차량용도가해자'], axis = 1, inplace = True)

* 차량용도피해자_대분류, 차량용도피해자_중분류, 차량용도피해자 - 중분류 속성만 살려서 더미변수화
* 사업용/비사업용 구분 없이 묶어버리기 - 결론 : 중분류만 살려서 더미변수화
* 버스종류는 버스로 묶기

In [123]:
#차량용도피해자
pd.DataFrame(df.groupby(['차량용도피해자_대분류', '차량용도피해자_중분류', '차량용도피해자'])['빈도 수'].count())

                                     빈도 수
차량용도피해자_대분류 차량용도피해자_중분류 차량용도피해자
개인형이동수단(PM) 개인형이동수단(PM) 개인형이동수단(PM)    50
기타불명        기타불명        기타/불명           3
보행자         보행자         보행자            82
불명          불명          불명              3
비사업용        기타/건설기계     기타/건설기계         3
            버스          버스              6
            비사업용기타      비사업용기타          4
            승용차         승용차           231
            어린이통학버스     어린이통학버스         1
            화물차         화물차            25
사업용         노선버스        시내버스            6
            렌터카         렌터카            15
            사업용기타       기타              3
            전세버스        전세버스            5
            콘크리트믹서      콘크리트믹서          1
            택시          개인택시           16
                        법인택시           22
            화물차         일반화물            1
                        화물차             7
없음          없음          없음             29
원동기장치자전거    원동기장치자전거    원동기장치자전거      311
이륜차         이륜차         이륜차            24
자전거         자전거         자전거           975

In [124]:
df['차량용도피해자'].unique()

array(['자전거', '원동기장치자전거', '개인택시', '화물차', '보행자', '기타/불명', '렌터카', '비사업용기타',
       '승용차', '이륜차', '기타', '법인택시', '없음', '버스', '일반화물', '전세버스', '콘크리트믹서',
       '기타/건설기계', '시내버스', '개인형이동수단(PM)', '어린이통학버스', '불명'], dtype=object)

* 버스 : 버스, 노선버스, 전세버스, 어린이통학버스
* 기타 : 불명, 기타/건설기계, 기타불명, 비사업용기타, 사업용기타, 없음
* 자전거 : 원동기장치자전거, 자전거

In [125]:
df.loc[(df['차량용도피해자_중분류'] == '자전거'), '차량용도피해자'] = '피해자_차량용도_자전거'
df.loc[(df['차량용도피해자_중분류'] == '원동기장치자전거'), '차량용도피해자'] = '피해자_차량용도_자전거'
df.loc[(df['차량용도피해자_중분류'] == '택시'), '차량용도피해자'] = '피해자_차량용도_택시'
df.loc[(df['차량용도피해자_중분류'] == '화물차'), '차량용도피해자'] = '피해자_차량용도_화물차'
df.loc[(df['차량용도피해자_중분류'] == '보행자'), '차량용도피해자'] = '피해자_차량용도_보행자'
df.loc[(df['차량용도피해자_중분류'] == '기타불명'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '렌터카'), '차량용도피해자'] = '피해자_차량용도_렌터카'
df.loc[(df['차량용도피해자_중분류'] == '비사업용기타'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '승용차'), '차량용도피해자'] = '피해자_차량용도_승용차'
df.loc[(df['차량용도피해자_중분류'] == '이륜차'), '차량용도피해자'] = '피해자_차량용도_이륜차'
df.loc[(df['차량용도피해자_중분류'] == '사업용기타'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '없음'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '버스'), '차량용도피해자'] = '피해자_차량용도_버스'
df.loc[(df['차량용도피해자_중분류'] == '전세버스'), '차량용도피해자'] = '피해자_차량용도_버스'
df.loc[(df['차량용도피해자_중분류'] == '콘크리트믹서'), '차량용도피해자'] = '피해자_차량용도_콘크리트믹서'
df.loc[(df['차량용도피해자_중분류'] == '기타/건설기계'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '노선버스'), '차량용도피해자'] = '피해자_차량용도_버스'
df.loc[(df['차량용도피해자_중분류'] == '개인용이동수단(PM)'), '차량용도피해자'] = '피해자_차량용도_PM'
df.loc[(df['차량용도피해자_중분류'] == '어린이통학버스'), '차량용도피해자'] = '피해자_차량용도_버스'
df.loc[(df['차량용도피해자_중분류'] == '불명'), '차량용도피해자'] = '피해자_차량용도_기타'

In [126]:
df_차량용도피해자_dummies = pd.get_dummies(data = df['차량용도피해자'])
df_차량용도피해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_차량용도피해자_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,차량용도피해자_대분류,차량용도피해자_중분류,차량용도피해자,...,피해자_차량용도_기타,피해자_차량용도_렌터카,피해자_차량용도_버스,피해자_차량용도_보행자,피해자_차량용도_승용차,피해자_차량용도_이륜차,피해자_차량용도_자전거,피해자_차량용도_콘크리트믹서,피해자_차량용도_택시,피해자_차량용도_화물차
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,자전거,자전거,피해자_차량용도_자전거,...,0,0,0,0,0,0,1,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,자전거,자전거,피해자_차량용도_자전거,...,0,0,0,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,자전거,자전거,피해자_차량용도_자전거,...,0,0,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,자전거,자전거,피해자_차량용도_자전거,...,0,0,0,0,0,0,1,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,자전거,자전거,피해자_차량용도_자전거,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,개인형이동수단(PM),개인형이동수단(PM),개인형이동수단(PM),...,0,0,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,개인형이동수단(PM),개인형이동수단(PM),개인형이동수단(PM),...,0,0,0,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,개인형이동수단(PM),개인형이동수단(PM),개인형이동수단(PM),...,0,0,0,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,개인형이동수단(PM),개인형이동수단(PM),개인형이동수단(PM),...,0,0,0,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,개인형이동수단(PM),개인형이동수단(PM),개인형이동수단(PM),...,0,0,0,0,0,0,0,0,0,0

In [127]:
df.drop(['차량용도피해자_대분류','차량용도피해자_중분류','차량용도피해자'], axis = 1, inplace = True)

* 도로종류가 사고에 미치는 영향이 미미할 것이라 판단하여 전처리하지 않음. (컬럼제거)

In [128]:
df['도로종류'].unique()

array(['시도', '기타', '일반국도', '지방도', '군도'], dtype=object)

In [129]:
df.drop('도로종류', axis = 1, inplace = True)

* 도로형태_대분류, 도로형태 : 도형 + 대분류 + 도로형태 컬럼명으로 더미변수 생성 후 컬럼 제거

In [130]:
pd.DataFrame(df.groupby(['도로형태_대분류','도로형태'])['빈도 수'].count())

                    빈도 수
도로형태_대분류 도로형태
교차로      교차로내        679
         교차로부근       298
         교차로횡단보도내    165
기타       기타           35
기타/불명    기타/불명         8
단일로      기타단일로       541
         지하차도(도로)내    76
         횡단보도부근        3
         횡단보도상        11
불명       불명            3
주차장      주차장           4

In [131]:
#도로형태_교차로
df.loc[df['도로형태'] == '교차로내', '도로형태'] = '도형_교차로_교차로내'
df.loc[df['도로형태'] == '교차로부근', '도로형태'] = '도형_교차로_교차로부근'
df.loc[df['도로형태'] == '교차로횡단보도내', '도로형태'] = '도형_교차로_교차로횡단보도내'

#도로형태_기타
df.loc[df['도로형태'] == '기타', '도로형태'] = '도형_기타_기타'

#도로형태_기타/불명
df.loc[df['도로형태'] == '기타/불명', '도로형태'] = '도형_기타_기타'

# 도로형태_단일로
df.loc[df['도로형태'] == '기타단일로', '도로형태'] = '도형_단일로_기타단일로'
df.loc[df['도로형태'] == '지하차도(도로)내', '도로형태'] = '도형_단일로_지하차도(도로)내'
df.loc[df['도로형태'] == '횡단보도부근', '도로형태'] = '도형_단일로_횡단보도부근'
df.loc[df['도로형태'] == '횡단보도상', '도로형태'] = '도형_단일로_횡단보도상'

#도로형태_불명
df.loc[df['도로형태'] == '불명', '도로형태'] = '도형_기타_기타'


#도로형태_주차장
df.loc[df['도로형태'] == '주차장', '도로형태'] = '도형_주차장_주차장'

* '기타'로 통일 : 기타, 기타/불명, 불명 / 더미변수 생성 후에 '기타' 컬럼 제거 고려

In [132]:
df['도로형태'].unique()

array(['도형_교차로_교차로내', '도형_기타_기타', '도형_단일로_기타단일로', '도형_교차로_교차로부근',
       '도형_교차로_교차로횡단보도내', '도형_단일로_지하차도(도로)내', '도형_주차장_주차장',
       '도형_단일로_횡단보도상', '도형_단일로_횡단보도부근'], dtype=object)

In [133]:
도로형태_dummies = pd.get_dummies(df['도로형태'])
도로형태_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 도로형태_dummies, how = 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,도로형태_대분류,도로형태,노인보호구역_여부,...,피해자_차량용도_화물차,도형_교차로_교차로내,도형_교차로_교차로부근,도형_교차로_교차로횡단보도내,도형_기타_기타,도형_단일로_기타단일로,도형_단일로_지하차도(도로)내,도형_단일로_횡단보도부근,도형_단일로_횡단보도상,도형_주차장_주차장
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,교차로,도형_교차로_교차로내,아니오,...,0,1,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,교차로,도형_교차로_교차로내,아니오,...,0,1,0,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,교차로,도형_교차로_교차로내,아니오,...,0,1,0,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,기타,도형_기타_기타,아니오,...,0,0,0,0,1,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,단일로,도형_단일로_기타단일로,아니오,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,교차로,도형_교차로_교차로부근,아니오,...,0,0,1,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,단일로,도형_단일로_기타단일로,아니오,...,0,0,0,0,0,1,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,교차로,도형_교차로_교차로부근,아니오,...,0,0,1,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,단일로,도형_단일로_기타단일로,아니오,...,0,0,0,0,0,1,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,교차로,도형_교차로_교차로부근,아니오,...,0,0,1,0,0,0,0,0,0,0

In [134]:
df.drop(['도로형태_대분류','도로형태'], axis = 1, inplace = True) #도로형태 대분류, 도로형태 컬럼 제거

In [135]:
df['노인보호구역_여부'].unique()

array(['아니오', '예'], dtype=object)

In [136]:
#노인보호구역_여부
mapping = {'아니오': 0,
           '예': 1}
df['노인보호구역_여부'] = df['노인보호구역_여부'].map(mapping)

In [137]:
df['노인보호구역_여부'].unique()

array([0, 1], dtype=int64)

In [138]:
df['어린이보호구역_여부'].unique()

array(['아니오', '예'], dtype=object)

In [139]:
mapping = {'아니오': 0,
           '예': 1}
df['어린이보호구역_여부'] = df['어린이보호구역_여부'].map(mapping)

In [140]:
df['어린이보호구역_여부'].unique()

array([0, 1], dtype=int64)

In [141]:
df['자전거도로_여부'].unique()

array(['아니오', nan, '예'], dtype=object)

In [142]:
df['자전거도로_여부'] = df['자전거도로_여부'].fillna('아니오')

* 일단 nan값을 '아니오'로 채워놓음. 검토 필요.

In [143]:
df['자전거도로_여부'].unique()

array(['아니오', '예'], dtype=object)

In [144]:
# 자전거도로
mapping = {'아니오' : 0, 
           '예' : 1 }
df['자전거도로_여부'] = df['자전거도로_여부'].map(mapping)

In [145]:
df['자전거도로_여부'].unique()

array([0, 1], dtype=int64)

In [146]:
#'도로선형_대분류', '도로선형_중분류', '도로선형' : 중분류 고려 x / 더미변수 생성
pd.DataFrame(df.groupby(['도로선형_대분류', '도로선형_중분류', '도로선형'])['빈도 수'].count())

                            빈도 수
도로선형_대분류 도로선형_중분류 도로선형
기타구역     기타구역     기타/서비스구역    17
직선       직선       내리막        101
                  오르막         67
                  평지        1575
커브ㆍ곡각    우        내리막          7
                  오르막          7
                  평지          22
         좌        내리막          4
                  오르막          7
                  평지          16

In [147]:
#도로선형_기타구역
df.loc[(df['도로선형_대분류'] == '기타구역') & (df['도로선형'] == '기타/서비스구역'), '도로선형'] = '도로선형_기타_기타'

# 도로선형_직선
df.loc[(df['도로선형_대분류'] == '직선') & (df['도로선형'] == '내리막'), '도로선형'] = '도로선형_직선_내리막'
df.loc[(df['도로선형_대분류'] == '직선') & (df['도로선형'] == '평지'), '도로선형'] = '도로선형_직선_평지'
df.loc[(df['도로선형_대분류'] == '직선') & (df['도로선형'] == '오르막'), '도로선형'] = '도로선형_직선_오르막'

#도로선형_커브곡각
df.loc[(df['도로선형_대분류'] == '커브ㆍ곡각 ') & (df['도로선형'] == '평지'), '도로선형'] = '도로선형_커브곡각_평지'
df.loc[(df['도로선형_대분류'] == '커브ㆍ곡각 ') & (df['도로선형'] == '내리막'), '도로선형'] = '도로선형_커브곡각_내리막'
df.loc[(df['도로선형_대분류'] == '커브ㆍ곡각 ') & (df['도로선형'] == '오르막'), '도로선형'] = '도로선형_커브곡각_오르막'

In [148]:
df['도로선형'].unique()

array(['도로선형_직선_내리막', '도로선형_직선_평지', '평지  ', '도로선형_직선_오르막', '도로선형_기타_기타',
       '도로선형_커브곡각_오르막', '도로선형_커브곡각_내리막'], dtype=object)

In [149]:
도로선형_dummies = pd.get_dummies(df['도로선형'])
도로선형_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 도로선형_dummies, how = 'outer', on = 'TAAS사고관리번호')

In [150]:
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,노인보호구역_여부,어린이보호구역_여부,자전거도로_여부,...,도형_단일로_횡단보도부근,도형_단일로_횡단보도상,도형_주차장_주차장,도로선형_기타_기타,도로선형_직선_내리막,도로선형_직선_오르막,도로선형_직선_평지,도로선형_커브곡각_내리막,도로선형_커브곡각_오르막,평지
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [151]:
df.drop(['도로선형_대분류', '도로선형_중분류', '도로선형'], axis = 1, inplace = True)

* '기상상태','노면상태_대분류', '노면상태', '교차로형태_대분류', '교차로형태',

In [152]:
df['기상상태'].unique()

array(['맑음', '비', '흐림', '안개', '기타/불명'], dtype=object)

In [153]:
#기상상태 : 더미변수
df_기상상태_dummies = pd.get_dummies(df['기상상태'])
df_기상상태_dummies.rename(columns  = {'기타/불명' : '기상상태_기타'}, inplace = True)
df_기상상태_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호'] #키 생성
df = pd.merge(df, df_기상상태_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,노인보호구역_여부,어린이보호구역_여부,자전거도로_여부,...,도로선형_직선_오르막,도로선형_직선_평지,도로선형_커브곡각_내리막,도로선형_커브곡각_오르막,평지,기상상태_기타,맑음,비,안개,흐림
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,0,0,0,...,0,1,0,0,0,0,1,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [154]:
df.drop('기상상태', axis = 1, inplace = True) #기상상태 컬럼 제거

In [155]:
#노면상태_대분류, 노면상태 : 컬럼 합쳐서 전처리
df['노면상태_대분류'].unique()

array(['포장', '비포장'], dtype=object)

In [156]:
df['노면상태'].unique()

array(['건조', '젖음/습기', '기타'], dtype=object)

In [157]:
pd.DataFrame(df.groupby(['노면상태_대분류','노면상태'])['빈도 수'].count())

                빈도 수
노면상태_대분류 노면상태
비포장      건조        1
         젖음/습기     1
포장       건조     1737
         기타        8
         젖음/습기    76

In [158]:
df.loc[(df['노면상태_대분류'] == '비포장') & (df['노면상태'] == '건조'), '노면상태'] = '비포장_건조'
df.loc[(df['노면상태_대분류'] == '비포장') & (df['노면상태'] == '젖음/습기'), '노면상태'] = '비포장_젖음/습기'
df.loc[(df['노면상태_대분류'] == '포장') & (df['노면상태'] == '건조') , '노면상태'] = '포장_건조'
df.loc[(df['노면상태_대분류'] == '포장') & (df['노면상태'] == '기타') , '노면상태'] = '포장_기타'
df.loc[(df['노면상태_대분류'] == '포장') & (df['노면상태'] == '젖음/습기') , '노면상태'] = '포장_젖음/습기'

In [159]:
df_노면상태_dummies = pd.get_dummies(df['노면상태'])
df_노면상태_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_노면상태_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,노인보호구역_여부,어린이보호구역_여부,자전거도로_여부,...,기상상태_기타,맑음,비,안개,흐림,비포장_건조,비포장_젖음/습기,포장_건조,포장_기타,포장_젖음/습기
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0

In [160]:
df.drop(['노면상태_대분류','노면상태'], axis = 1, inplace = True)

* 교차로형태_대분류, 교차로형태 : 교차로형태 컬럼으로 통일

In [161]:
pd.DataFrame(df.groupby(['교차로형태_대분류','교차로형태'])['빈도 수'].count())

                      빈도 수
교차로형태_대분류 교차로형태
교차로       교차로 - 사지     718
          교차로 - 삼지     373
          교차로 - 오지이상    47
          교차로 - 회전       4
교차로아님     교차로아님        681

In [162]:
df_교차로형태_dummies = pd.get_dummies(df['교차로형태'])
df_교차로형태_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_교차로형태_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,노인보호구역_여부,어린이보호구역_여부,자전거도로_여부,...,비포장_건조,비포장_젖음/습기,포장_건조,포장_기타,포장_젖음/습기,교차로 - 사지,교차로 - 삼지,교차로 - 오지이상,교차로 - 회전,교차로아님
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0

In [163]:
df.drop(['교차로형태_대분류','교차로형태'], axis = 1, inplace = True)

In [164]:
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,가해자_음주_여부,노인보호구역_여부,어린이보호구역_여부,자전거도로_여부,...,비포장_건조,비포장_젖음/습기,포장_건조,포장_기타,포장_젖음/습기,교차로 - 사지,교차로 - 삼지,교차로 - 오지이상,교차로 - 회전,교차로아님
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0

In [165]:
df.to_csv("C:/Users/user/Desktop/자전거PM사고_청주_cleaned.csv",header = True, index = False, encoding = 'cp949')