### 필요 모듈 임포트

In [1]:
import pandas as pd
import os
os.getcwd()

'C:\\Users\\user\\Desktop'

### 파일 불러오기 / 파일 합치기
* 피해자전거 : 발생지_시군구 '청주시', 차량용도피해자_대분류 : '원동기장치자전거', '자전거'
* 피해자전거 : 자전거
* 가해pm, 피해pm : 발생지_시군구 '청주시'

In [2]:
가해자전거 = pd.read_csv('2016_2020_가해자자전거사고정보.csv', encoding ='cp949')

In [3]:
피해자전거 = pd.read_csv('2016_2020_2당사자_이륜차자전거.csv', encoding = 'cp949')

In [4]:
가해pm = pd.read_csv('2016_2020_가해자개인형이동수단(PM)사고정보.csv', encoding = 'cp949')

In [5]:
피해pm = pd.read_excel('피해자PM사고데이터_2016_2020.xlsx')

In [6]:
피해자전거['차량용도피해자_대분류'].unique()

array(['원동기장치자전거', '이륜차', '자전거', '사륜오토바이(ATV)'], dtype=object)

In [7]:
피해자전거_ = 피해자전거.loc[((피해자전거['발생지_시군구'] == '청주시') & (피해자전거['차량용도피해자_대분류'] == '원동기장치자전거')) 
                            | ((피해자전거['발생지_시군구'] == '청주시')    & (피해자전거['차량용도피해자_대분류'] == '자전거'))]

In [8]:
# And , Or 조건 확인용
피해자전거_[피해자전거_['차량용도피해자_대분류'] == '원동기장치자전거']

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
40183,2020082900100303,2020082914,충북,청주시,998884.0,1848226.0,토,주,사망,차대차,...,평지,맑음,포장,젖음/습기,교차로,교차로 - 삼지,1,0,0,0
40197,2020062000100206,2020062011,충북,청주시,1000808.0,1846239.0,토,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,1,2,0
40205,2020041100100382,2020041117,충북,청주시,998131.0,1851065.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
40234,2019070600100170,2019070608,충북,청주시,993992.0,1840060.0,토,주,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
40242,2019072700100391,2019072715,충북,청주시,1000234.0,1846584.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43186,2017060400100021,2017060400,충북,청주시,998129.0,1849132.0,일,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
43193,2016092500100422,2016092519,충북,청주시,996553.0,1849308.0,일,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
43194,2016090400100426,2016090420,충북,청주시,993677.0,1849341.0,일,야,경상,차대차,...,평지,흐림,포장,건조,교차로,교차로 - 삼지,0,0,1,0
43197,2016022100100418,2016022121,충북,청주시,992591.0,1849853.0,일,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,1,0,0
43198,2016020700100042,2016020702,충북,청주시,996357.0,1850159.0,일,야,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0

In [9]:
# And , Or 조건 확인용
피해자전거_[피해자전거_['차량용도피해자_대분류'] == '자전거']

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
40170,2020082200100432,2020082217,충북,청주시,1000111.0,1845339.0,토,주,경상,차대차,...,내리막,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
40175,2020080100100116,2020080109,충북,청주시,993596.0,1848445.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
40176,2020092600100236,2020092611,충북,청주시,995526.0,1847649.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
40177,2020121200100323,2020121217,충북,청주시,995679.0,1851636.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
40178,2020062700100313,2020062714,충북,청주시,993695.0,1848615.0,토,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43195,2016070300100324,2016070318,충북,청주시,994273.0,1848720.0,일,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
43196,2016052900100081,2016052905,충북,청주시,994107.0,1846950.0,일,야,중상,차대차,...,오르막,흐림,포장,건조,교차로,교차로 - 사지,0,1,0,0
43199,2016121800100361,2016121819,충북,청주시,996145.5,1860242.9,일,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
43200,2016120400100311,2016120418,충북,청주시,998708.0,1849396.0,일,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
43201,2016103000100480,2016103020,충북,청주시,993728.0,1857719.0,일,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0

In [10]:
피해자전거 = 피해자전거_

In [11]:
피해자전거.columns

Index(['TAAS사고관리번호', '발생일시', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '사고유형_대분류', '사고유형_중분류', '사고유형', '성별가해자', '성별가해자_1',
       '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자', '보호장구가해자_대분류',
       '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자', '행동유형가해자_대분류',
       '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자', '가해자신체상해주부위',
       '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류', '당사자종별피해자',
       '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류', '차량용도피해자_중분류',
       '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부', '어린이보호구역_여부',
       '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태', '노면상태_대분류', '노면상태',
       '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수', '부상신고자수'],
      dtype='object')

In [12]:
가해자전거.columns

Index(['TAAS사고관리번호', '발생일시', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '사고유형_대분류', '사고유형_중분류', '사고유형', '성별가해자', '성별가해자_1',
       '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자', '보호장구가해자_대분류',
       '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자', '행동유형가해자_대분류',
       '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자', '가해자신체상해주부위',
       '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류', '당사자종별피해자',
       '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류', '차량용도피해자_중분류',
       '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부', '어린이보호구역_여부',
       '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태', '노면상태_대분류', '노면상태',
       '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수', '부상신고자수'],
      dtype='object')

In [13]:
가해자전거

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
0,2016011000100173,2016011013,서울,중구,957025.0,1951220.0,일,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
1,2016040600100064,2016040607,서울,중구,955095.0,1951434.0,수,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
2,2016091600100358,2016091622,서울,중구,956689.0,1952364.0,금,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
3,2016041000100150,2016041011,서울,중구,954156.0,1951499.0,일,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,0,1
4,2016073000100378,2016073016,서울,중구,953802.0,1951722.0,토,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27661,2020090500100496,2020090520,대전,중구,989961.0,1813221.0,토,야,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
27662,2020091400100382,2020091416,서울,영등포구,946934.0,1943521.0,월,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
27663,2020091800100653,2020091821,서울,영등포구,948678.0,1947142.0,금,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
27664,2020071800100511,2020071819,광주,북구,943114.0,1693715.0,토,야,중상,차대차,...,평지,흐림,포장,젖음/습기,교차로아님,교차로아님,0,1,1,0
27665,2020090900100491,2020090921,서울,강남구,960448.0,1947799.0,수,야,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0

In [14]:
가해자전거[가해자전거['발생지_시군구'] == '청주시']
# 가해자전거.loc[(가해자전거['발생지_시군구'] == '청주시')] : loc 사용해도 무방함. 위에 쓴 코드가 더 간단함

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
3312,2016012300100336,2016012317,충북,청주시,1003039.0,1858217.0,토,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
3313,2016013000100421,2016013016,충북,청주시,999412.0,1852015.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
3314,2016030300100460,2016030319,충북,청주시,997192.0,1847998.0,목,야,경상,차대사람,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
3315,2016031600100327,2016031615,충북,청주시,998483.0,1850590.0,수,주,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
3316,2016032800100485,2016032818,충북,청주시,998448.0,1849225.0,월,야,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27426,2020092200100513,2020092217,충북,청주시,999944.0,1847639.0,화,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
27434,2020081000100277,2020081014,충북,청주시,993755.0,1849051.0,월,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
27508,2020100200100117,2020100212,충북,청주시,1000083.0,1843010.0,금,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
27513,2020082100100135,2020082109,충북,청주시,998861.0,1847468.0,금,주,경상,차대차,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
27533,2020120800100079,2020120808,충북,청주시,996956.0,1847716.0,화,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,0,1

In [15]:
가해자전거 = 가해자전거[가해자전거['발생지_시군구'] == '청주시']

In [16]:
피해자전거.columns != 가해자전거.columns #컬럼 일치여부 확인

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [17]:
피해자전거.shape #자전거 , 원동기장치자전거

(1286, 58)

In [18]:
가해자전거.shape #자전거

(486, 58)

In [19]:
pd.concat([피해자전거, 가해자전거])

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
40170,2020082200100432,2020082217,충북,청주시,1000111.0,1845339.0,토,주,경상,차대차,...,내리막,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
40175,2020080100100116,2020080109,충북,청주시,993596.0,1848445.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
40176,2020092600100236,2020092611,충북,청주시,995526.0,1847649.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
40177,2020121200100323,2020121217,충북,청주시,995679.0,1851636.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
40178,2020062700100313,2020062714,충북,청주시,993695.0,1848615.0,토,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27426,2020092200100513,2020092217,충북,청주시,999944.0,1847639.0,화,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
27434,2020081000100277,2020081014,충북,청주시,993755.0,1849051.0,월,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
27508,2020100200100117,2020100212,충북,청주시,1000083.0,1843010.0,금,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
27513,2020082100100135,2020082109,충북,청주시,998861.0,1847468.0,금,주,경상,차대차,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
27533,2020120800100079,2020120808,충북,청주시,996956.0,1847716.0,화,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,0,1

In [20]:
자전거 = pd.concat([피해자전거, 가해자전거]) #1772 rows × 58 columns

In [21]:
가해pm[가해pm['발생지_시군구'] == '청주시']

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
65,2017053100100361,2017053116,충북,청주시,997977.0,1849365.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
67,2017091600100635,2017091623,충북,청주시,984790.0,1848063.0,토,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
68,2017110500100465,2017110520,충북,청주시,996273.0,1850282.0,일,야,경상,차대차,...,오르막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
69,2017100300100168,2017100312,충북,청주시,999022.0,1848650.0,화,주,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
70,2017102500100150,2017102508,충북,청주시,997562.0,1845996.0,수,주,경상,차대사람,...,기타/서비스구역,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
71,2017110600100605,2017110621,충북,청주시,1001615.0,1847855.0,월,야,부상신고,차대차,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
228,2018071800100476,2018071818,충북,청주시,998820.0,1849695.0,수,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
229,2018022800100084,2018022808,충북,청주시,993807.0,1857498.0,수,주,중상,차대차,...,평지,비,포장,젖음/습기,교차로아님,교차로아님,0,1,0,0
230,2018121600100143,2018121611,충북,청주시,991748.0,1859087.0,일,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,2,0
231,2018050900100110,2018050908,충북,청주시,996102.0,1848470.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
236,2018103000100679,2018103022,충북,청주시,995530.0,1847811.0,화,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
237,2018111400100069,2018111407,충북,청주시,998707.0,1848630.0,수,주,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
238,2018061600100494,2018061619,충북,청주시,1000534.2,1847934.4,토,야,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
239,2018092500100413,2018092520,충북,청주시,999024.0,1847421.0,화,야,경상,차대사람,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
240,2018082800100352,2018082816,충북,청주시,998901.0,1848005.0,화,주,부상신고,차량단독,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,0,1
241,2018073000100024,2018073002,충북,청주시,999302.0,1847673.0,월,야,경상,차량단독,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
242,2018090200100240,2018090214,충북,청주시,998519.0,1845762.0,일,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,2,0
243,2018090200100281,2018090216,충북,청주시,998731.0,1847654.0,일,주,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
244,2018082900100342,2018082916,충북,청주시,999031.0,1848566.0,수,주,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
378,2019081300100685,2019081322,충북,청주시,994896.0,1858444.0,화,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
399,2019073000100592,2019073020,충북,청주시,998328.4,1852067.1,화,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
409,2019052200100216,2019052209,충북,청주시,998265.0,1851654.0,수,주,경상,차량단독,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
620,2019093000100706,2019093022,충북,청주시,999899.0,1851973.0,월,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,2,0,0
623,2019110100100225,2019110109,충북,청주시,997226.0,1849085.0,금,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
628,2019121700100580,2019121721,충북,청주시,992973.0,1849021.0,화,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
630,2019122200100324,2019122216,충북,청주시,993194.0,1849803.0,일,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
635,2019040400100418,2019040416,충북,청주시,1001390.5,1846960.4,목,주,부상신고,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
638,2019042300100076,2019042307,충북,청주시,998592.0,1847035.0,화,주,중상,차대차,...,내리막,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
640,2019040100100495,2019040117,충북,청주시,994550.0,1848499.0,월,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
641,2019050100100462,2019050118,충북,청주시,993482.3,1849314.3,수,야,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
643,2019052200100453,2019052216,충북,청주시,996160.0,1849672.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
644,2019083000100743,2019083021,충북,청주시,998723.0,1845804.0,금,야,중상,차량단독,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
646,2019090300100677,2019090321,충북,청주시,1000880.0,1846591.0,화,야,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
647,2019091800100224,2019091811,충북,청주시,1000734.5,1845926.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
648,2019102800100095,2019102807,충북,청주시,1000040.0,1846315.0,월,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,0,1
649,2019112800100586,2019112819,충북,청주시,1000290.0,1845846.0,목,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
877,2020070600100099,2020070608,충북,청주시,995442.0,1850157.0,월,주,중상,차대차,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
897,2020041300100433,2020041318,충북,청주시,996751.1,1847500.1,월,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
927,2020120200100539,2020120221,충북,청주시,998147.0,1850997.0,수,야,중상,차대사람,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
931,2020082000100564,2020082020,충북,청주시,993041.0,1849259.0,목,야,부상신고,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,0,1
942,2020100800100088,2020100807,충북,청주시,995111.0,1848202.0,목,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,1
957,2020071500100329,2020071515,충북,청주시,996252.0,1848564.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
958,2020091300100308,2020091316,충북,청주시,999774.0,1845542.0,일,주,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
1005,2020021900100415,2020021916,충북,청주시,1000993.0,1847095.0,수,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
1330,2020102700100457,2020102717,충북,청주시,993589.0,1847299.0,화,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,2,0
1512,2020122300100541,2020122320,충북,청주시,984515.0,1847313.0,수,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0

In [22]:
가해pm = 가해pm[가해pm['발생지_시군구'] == '청주시']

In [23]:
가해pm.shape

(46, 58)

In [24]:
피해pm[피해pm['발생지_시군구'] == '청주시']

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
5,2020092200100455,2020092216,충북,청주시,993737.0,1856469.0,화,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
13,2020101400100242,2020101412,충북,청주시,993763.0,1847164.0,수,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
54,2020091400100440,2020091417,충북,청주시,995124.7,1850151.7,월,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,1,0,0
81,2020111000100493,2020111017,충북,청주시,984835.0,1848215.0,화,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
111,2020121600100303,2020121616,충북,청주시,996161.0,1848551.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
125,2020070100100352,2020070116,충북,청주시,998956.0,1851065.0,수,주,경상,차대차,...,오르막,맑음,포장,건조,교차로,교차로 - 오지이상,0,0,1,0
166,2020032200100279,2020032217,충북,청주시,1000624.0,1847892.0,일,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
251,2020092800100381,2020092814,충북,청주시,993467.0,1856434.0,월,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
257,2020061100100331,2020061114,충북,청주시,996578.1,1849306.4,목,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
259,2020091900100474,2020091916,충북,청주시,998133.0,1848897.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
305,2020080900100226,2020080915,충북,청주시,1013842.0,1848166.0,일,주,경상,차대차,...,평지,흐림,포장,건조,교차로,교차로 - 사지,0,0,1,0
390,2019031100100082,2019031107,충북,청주시,999451.0,1848731.0,월,주,경상,차대차,...,내리막,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
392,2019052400100427,2019052415,충북,청주시,993800.0,1849306.0,금,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
394,2019062300100426,2019062317,충북,청주시,998420.3,1847906.8,일,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
397,2019030700100413,2019030717,충북,청주시,995515.9,1848506.9,목,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,2,0
398,2019040300100286,2019040313,충북,청주시,996760.0,1847505.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
400,2019032600100135,2019032608,충북,청주시,999579.0,1846571.0,화,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,1,0,0
403,2019012500100151,2019012509,충북,청주시,997736.0,1847811.0,금,주,경상,차대차,...,내리막,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
405,2019092600100398,2019092616,충북,청주시,998622.0,1850359.0,목,주,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
509,2019102500100423,2019102515,충북,청주시,998790.0,1848228.0,금,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
595,2018102100100293,2018102115,충북,청주시,997735.0,1846491.0,일,주,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
596,2018042800100409,2018042815,충북,청주시,998992.0,1847789.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
597,2018112700100109,2018112708,충북,청주시,993532.0,1856664.0,화,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
598,2018080100100407,2018080116,충북,청주시,996709.0,1848478.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
599,2018061900100279,2018061913,충북,청주시,998446.0,1849930.0,화,주,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
600,2018121400100356,2018121415,충북,청주시,997406.0,1851511.0,금,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
657,2018062100100424,2018062117,충북,청주시,994233.0,1850293.0,목,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
730,2020092400100546,2020092419,충북,청주시,993677.0,1857523.0,목,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
746,2020081300100620,2020081323,충북,청주시,995033.0,1858752.0,목,야,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
759,2020112500100577,2020112521,충북,청주시,996447.0,1848444.0,수,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,2,0
772,2020111700100656,2020111723,충북,청주시,995816.0,1859920.0,화,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,1,0,0
820,2020082900100008,2020082900,충북,청주시,1000642.0,1845652.0,토,야,중상,차대차,...,평지,비,포장,젖음/습기,교차로,교차로 - 사지,0,1,0,0
930,2020020700100642,2020020721,충북,청주시,993754.0,1857011.0,금,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1135,2019082600100661,2019082621,충북,청주시,993950.0,1847275.0,월,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1137,2019021300100503,2019021320,충북,청주시,997027.0,1847465.0,수,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1138,2019110400100762,2019110422,충북,청주시,997320.8,1846557.5,월,야,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
1141,2019102200100665,2019102220,충북,청주시,1000402.0,1845551.0,화,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1146,2019102800100548,2019102818,충북,청주시,998355.0,1849860.0,월,야,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
1147,2019100700100533,2019100718,충북,청주시,999347.0,1851676.0,월,야,중상,차대차,...,평지,비,포장,젖음/습기,교차로,교차로 - 사지,0,1,0,0
1150,2019052900100725,2019052923,충북,청주시,993114.0,1855561.0,수,야,중상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,1,0,0
1332,2018072500100552,2018072520,충북,청주시,999400.0,1847801.0,수,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
1333,2018070500100520,2018070520,충북,청주시,998802.0,1848227.0,목,야,중상,차대차,...,평지,비,포장,젖음/습기,교차로아님,교차로아님,0,1,0,0
1334,2018042000100034,2018042002,충북,청주시,997373.0,1846008.0,금,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1335,2018051000100493,2018051018,충북,청주시,994463.0,1847557.0,목,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1337,2018080700100036,2018080703,충북,청주시,983171.0,1860952.0,화,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1338,2018041900100012,2018041900,충북,청주시,998267.0,1852140.0,목,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,1,0
1339,2018071900100710,2018071923,충북,청주시,997198.0,1847791.0,목,야,경상,차대차,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1383,2018011300100473,2018011320,충북,청주시,998501.0,1852654.0,토,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1427,2017102000100588,2017102018,충북,청주시,993500.0,1848011.0,금,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1428,2017091300100523,2017091318,충북,청주시,995354.0,1848473.0,수,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 오지이상,0,0,1,0

In [25]:
피해pm = 피해pm[피해pm['발생지_시군구'] == '청주시']

In [26]:
피해pm.shape

(50, 58)

In [27]:
자전거.columns != 가해pm.columns

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [28]:
 가해pm.columns != 피해pm.columns #일치하지 않는 컬럼 발견

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [29]:
피해pm.rename(columns= {'성별가해자.1': '성별가해자_1'}, inplace = True) #해당 컬럼 변경

In [30]:
피해pm.columns != 가해pm.columns #일치여부 확인

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [31]:
pd.concat([가해pm, 피해pm])

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
65,2017053100100361,2017053116,충북,청주시,997977.0,1849365.0,수,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
67,2017091600100635,2017091623,충북,청주시,984790.0,1848063.0,토,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,0,0
68,2017110500100465,2017110520,충북,청주시,996273.0,1850282.0,일,야,경상,차대차,...,오르막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
69,2017100300100168,2017100312,충북,청주시,999022.0,1848650.0,화,주,경상,차대사람,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
70,2017102500100150,2017102508,충북,청주시,997562.0,1845996.0,수,주,경상,차대사람,...,기타/서비스구역,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1338,2018041900100012,2018041900,충북,청주시,998267.0,1852140.0,목,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,1,0
1339,2018071900100710,2018071923,충북,청주시,997198.0,1847791.0,목,야,경상,차대차,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1383,2018011300100473,2018011320,충북,청주시,998501.0,1852654.0,토,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1427,2017102000100588,2017102018,충북,청주시,993500.0,1848011.0,금,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1428,2017091300100523,2017091318,충북,청주시,995354.0,1848473.0,수,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 오지이상,0,0,1,0

In [32]:
pm사고 = pd.concat([가해pm, 피해pm])

In [33]:
pd.concat([자전거, pm사고])

,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
40170,2020082200100432,2020082217,충북,청주시,1000111.0,1845339.0,토,주,경상,차대차,...,내리막,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
40175,2020080100100116,2020080109,충북,청주시,993596.0,1848445.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
40176,2020092600100236,2020092611,충북,청주시,995526.0,1847649.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
40177,2020121200100323,2020121217,충북,청주시,995679.0,1851636.0,토,주,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
40178,2020062700100313,2020062714,충북,청주시,993695.0,1848615.0,토,주,부상신고,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1338,2018041900100012,2018041900,충북,청주시,998267.0,1852140.0,목,야,중상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,1,0
1339,2018071900100710,2018071923,충북,청주시,997198.0,1847791.0,목,야,경상,차대차,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1383,2018011300100473,2018011320,충북,청주시,998501.0,1852654.0,토,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1427,2017102000100588,2017102018,충북,청주시,993500.0,1848011.0,금,야,경상,차대차,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1428,2017091300100523,2017091318,충북,청주시,995354.0,1848473.0,수,야,경상,차대차,...,평지,맑음,포장,건조,교차로,교차로 - 오지이상,0,0,1,0

In [34]:
자전거PM사고 = pd.concat([자전거, pm사고])

In [35]:
df = 자전거PM사고 #간편한 입력을 위해 변경

In [36]:
중복 = pd.DataFrame(df['TAAS사고관리번호'].value_counts()) #중복되는 컬럼 존재 확인
len(중복[중복['TAAS사고관리번호'] == 2])

45

In [37]:
print(len(df['TAAS사고관리번호'])) 
len(df['TAAS사고관리번호'].unique()) #두 값이 일치하지 않는다는 것으로 중복되는 값의 존재 확인

1868

1823

In [38]:
df.drop_duplicates(inplace=True)
# 피해,가해 사고 중복 컬럼 제거 ex)가해자(자전거) - 피해자(자전거) 인 경우 두 테이블에 다 포함되어 있어 중복 제거
df.shape

(1823, 58)

In [39]:
df.to_csv("C:/Users/user/Desktop/자전거PM사고_청주.csv",header = True, index = False, encoding = 'cp949') #header, index = False

### 컬럼 전처리 (순서 변수 / 더미 변수)

In [40]:
import pandas as pd
df = pd.read_csv("C:/Users/user/Desktop/자전거PM사고_청주.csv",encoding = 'cp949')
df.shape
#index가 뒤죽박죽인 것을 확인할 수 있음.
#인덱스 번호 error로 인한 오류 있었음. 
# df = df.reset_index() 코드로 해결함 (index 새로 설정)

(1823, 58)

In [41]:
df = df.reset_index() #인덱스 분리

In [42]:
df

,index,TAAS사고관리번호,발생일시,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,...,도로선형,기상상태,노면상태_대분류,노면상태,교차로형태_대분류,교차로형태,사망자수,중상자수,경상자수,부상신고자수
0,0,2020082200100432,2020082217,충북,청주시,1000111.0,1845339.0,토,주,경상,...,내리막,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1,1,2020080100100116,2020080109,충북,청주시,993596.0,1848445.0,토,주,경상,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
2,2,2020092600100236,2020092611,충북,청주시,995526.0,1847649.0,토,주,경상,...,평지,맑음,포장,건조,교차로,교차로 - 삼지,0,0,1,0
3,3,2020121200100323,2020121217,충북,청주시,995679.0,1851636.0,토,주,경상,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
4,4,2020062700100313,2020062714,충북,청주시,993695.0,1848615.0,토,주,부상신고,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,2018041900,충북,청주시,998267.0,1852140.0,목,야,중상,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,1,1,0
1819,1819,2018071900100710,2018071923,충북,청주시,997198.0,1847791.0,목,야,경상,...,내리막,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1820,1820,2018011300100473,2018011320,충북,청주시,998501.0,1852654.0,토,야,경상,...,평지,맑음,포장,건조,교차로,교차로 - 사지,0,0,1,0
1821,1821,2017102000100588,2017102018,충북,청주시,993500.0,1848011.0,금,야,경상,...,평지,맑음,포장,건조,교차로아님,교차로아님,0,0,1,0
1822,1822,2017091300100523,2017091318,충북,청주시,995354.0,1848473.0,수,야,경상,...,평지,맑음,포장,건조,교차로,교차로 - 오지이상,0,0,1,0

In [43]:
df.columns #컬럼명 확인

Index(['index', 'TAAS사고관리번호', '발생일시', '발생지_시도', '발생지_시군구', 'X_POINT',
       'Y_POINT', '요일', '주야', '사고내용', '사고유형_대분류', '사고유형_중분류', '사고유형', '성별가해자',
       '성별가해자_1', '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자',
       '보호장구가해자_대분류', '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자',
       '행동유형가해자_대분류', '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자',
       '가해자신체상해주부위', '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류',
       '당사자종별피해자', '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류',
       '차량용도피해자_중분류', '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부',
       '어린이보호구역_여부', '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태',
       '노면상태_대분류', '노면상태', '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수',
       '부상신고자수'],
      dtype='object')

In [44]:
df['발생일시']

0       2020082217
1       2020080109
2       2020092611
3       2020121217
4       2020062714
           ...
1818    2018041900
1819    2018071923
1820    2018011320
1821    2017102018
1822    2017091318
Name: 발생일시, Length: 1823, dtype: int64

In [45]:
# 발생일시 -> datetime 으로 변환 -> date 컬럼 생성후 발생일시 컬럼 삭제
# 날짜 변환
df['year'] = df['발생일시'].astype(str)

In [46]:
year = []
for i in range(len(df['year'])):
    a = df['year'][i][0:4]
    year.append(a)
df['year'] = year

In [47]:
df['year']

0       2020
1       2020
2       2020
3       2020
4       2020
        ...
1818    2018
1819    2018
1820    2018
1821    2017
1822    2017
Name: year, Length: 1823, dtype: object

In [48]:
#위와 동일한 원리로 생성
df['month'] = df['발생일시'].astype(str)
month = []
for i in range(len(df['month'])):
    a = df['month'][i][4:6]
    month.append(a)
df['month'] = month

In [49]:
df['day'] = df['발생일시'].astype(str)
day = []
for i in range(len(df['day'])):
    a = df['day'][i][6:8]
    day.append(a)
df['day'] = day

In [50]:
df['hour'] = df['발생일시'].astype(str)
hour = []
for i in range(len(df['hour'])):
    a = df['hour'][i][-2:]
    hour.append(a)
df['hour'] = hour

In [51]:
df['date'] = df['year'] + '-' + df['month'] + '-' + df['day'] + ' ' + df['hour'] + ':00:00'
df['date'] = pd.to_datetime(df['date']) #datetime 으로 변환

In [52]:
df['date']

0      2020-08-22 17:00:00
1      2020-08-01 09:00:00
2      2020-09-26 11:00:00
3      2020-12-12 17:00:00
4      2020-06-27 14:00:00
               ...
1818   2018-04-19 00:00:00
1819   2018-07-19 23:00:00
1820   2018-01-13 20:00:00
1821   2017-10-20 18:00:00
1822   2017-09-13 18:00:00
Name: date, Length: 1823, dtype: datetime64[ns]

In [53]:
df.drop('발생일시', axis = 1, inplace = True) #axis = 0 : 행 / axis = 1 : 열 /inplace=True : 원본에서 바로 바꾸기.

In [54]:
df.drop(['year','month','day','hour'], axis = 1, inplace = True) #여러개 한꺼번에 삭제시 대괄호

In [55]:
df.columns

Index(['index', 'TAAS사고관리번호', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '사고유형_대분류', '사고유형_중분류', '사고유형', '성별가해자', '성별가해자_1',
       '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자', '보호장구가해자_대분류',
       '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자', '행동유형가해자_대분류',
       '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자', '가해자신체상해주부위',
       '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류', '당사자종별피해자',
       '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류', '차량용도피해자_중분류',
       '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부', '어린이보호구역_여부',
       '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태', '노면상태_대분류', '노면상태',
       '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수', '부상신고자수', 'date'],
      dtype='object')

* 발생지_시도, 발생지_시군구 : 충청북도, 청주시 로 공통이므로 전처리 생략
* 'X_POINT', 'Y_POINT' : 좌표이므로 생략

In [ ]:
#요일 : 순서변수 처리
mapping = {'월': 1, '화': 2, '수': 3,'목': 4, '금': 5, '토': 6, '일': 7 }
df['요일'] = df['요일'].map(mapping)

In [57]:
df['요일'].unique()

array([6, 5, 4, 3, 2, 1, 7], dtype=int64)

In [58]:
#주야 : 순서변수 -> mapping
# '주': 1, '야': 2
mapping = {'주': 1, 
           '야': 2}
df['주야'] = df['주야'].map(mapping)

In [59]:
df['주야'].unique()

array([1, 2], dtype=int64)

In [60]:
# 사고 심각수준에 따라 심각수준이 큰 변수에 큰 숫자부여 : 순서변수
mapping = {'부상신고' : 1,
           '경상' : 2,
           '중상' : 3,
           '사망' : 4 }
df['사고내용'] = df['사고내용'].map(mapping)

In [61]:
df['사고내용'].unique()

array([2, 1, 3, 4], dtype=int64)

In [62]:
df[['사고유형_중분류', '사고유형']]
#대부분의 '사고유형_중분류','사고유형' 일치하는 것으로 보임

     사고유형_중분류  사고유형
0          기타    기타
1          기타    기타
2          기타    기타
3          기타    기타
4        측면충돌  측면충돌
...       ...   ...
1818     측면충돌  측면충돌
1819       기타    기타
1820       기타    기타
1821     측면충돌  측면충돌
1822       기타    기타

[1823 rows x 2 columns]

In [63]:
#일치하지 않는 것 확인 - 같은 것으로 확인되었음
df[df['사고유형_중분류']!= df['사고유형']][['사고유형_중분류','사고유형']]

     사고유형_중분류     사고유형
380        추돌   진행중 추돌
497        추돌   진행중 추돌
695        추돌   진행중 추돌
753        추돌   진행중 추돌
879        추돌   진행중 추돌
895        추돌   진행중 추돌
951        추돌   진행중 추돌
959        추돌   진행중 추돌
1223       추돌   진행중 추돌
1277       추돌   진행중 추돌
1289       추돌   진행중 추돌
1321       추돌   진행중 추돌
1750     도로이탈  도로이탈 추락

In [64]:
df['빈도 수'] = 1

In [65]:
pd.DataFrame(df.groupby(['사고유형_대분류','사고유형_중분류'])['빈도 수'].count())

                     빈도 수
사고유형_대분류 사고유형_중분류
차대사람     기타            43
         길가장자리구역통행중     2
         보도통행중         13
         차도통행중          4
         횡단중           20
차대차      기타           671
         정면충돌         172
         추돌            45
         측면충돌         814
         후진중충돌         10
차량단독     공작물충돌          3
         기타            10
         도로이탈           1
         전도             7
         전도전복           7
         전복             1

In [66]:
#사고유형_대분류, 사고유형_중분류 -> 사고 유형 컬럼으로
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '기타'), '사고유형_중분류'] = '차대사람_기타'
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '길가장자리구역통행중'), '사고유형_중분류'] = '차대사람_길가장자리구역통행중'
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '보도통행중'), '사고유형_중분류'] = '차대사람_보도통행중'
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '차도통행중	'), '사고유형_중분류'] = '차대사람_차도통행중'
df.loc[(df['사고유형_대분류'] == '차대사람')&(df['사고유형_중분류'] == '횡단중'), '사고유형_중분류'] = '차대사람_횡단중'

df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '기타'), '사고유형_중분류'] = '차대차_기타'
df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '정면충돌'), '사고유형_중분류'] = '차대차_정면충돌'
df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '추돌'), '사고유형_중분류'] = '차대차_추돌'
df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '측면충돌'), '사고유형_중분류'] = '차대차_측면충돌'
df.loc[(df['사고유형_대분류'] == '차대차')&(df['사고유형_중분류'] == '후진중충돌'), '사고유형_중분류'] = '차대차_후진중충돌'

df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '공작물충돌'), '사고유형_중분류'] = '차량단독_공작물충돌'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '기타'), '사고유형_중분류'] = '차량단독_기타'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '도로이탈'), '사고유형_중분류'] = '차량단독_도로이탈'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '전도'), '사고유형_중분류'] = '차량단독_전도'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '전도전복'), '사고유형_중분류'] = '차량단독_전도전복'
df.loc[(df['사고유형_대분류'] == '차량단독')&(df['사고유형_중분류'] == '전복'), '사고유형_중분류'] = '차량단독_전복'

사고유형_dummies = pd.get_dummies(df['사고유형_중분류'])
사고유형_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 사고유형_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,사고유형_대분류,...,차대차_추돌,차대차_측면충돌,차대차_후진중충돌,차도통행중,차량단독_공작물충돌,차량단독_기타,차량단독_도로이탈,차량단독_전도,차량단독_전도전복,차량단독_전복
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,차대차,...,0,0,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,차대차,...,0,0,0,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,차대차,...,0,0,0,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,차대차,...,0,0,0,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,차대차,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,차대차,...,0,1,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,차대차,...,0,0,0,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,차대차,...,0,0,0,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,차대차,...,0,1,0,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,차대차,...,0,0,0,0,0,0,0,0,0,0

In [67]:
df.columns

Index(['index', 'TAAS사고관리번호', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '사고유형_대분류', '사고유형_중분류', '사고유형', '성별가해자', '성별가해자_1',
       '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자', '보호장구가해자_대분류',
       '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자', '행동유형가해자_대분류',
       '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자', '가해자신체상해주부위',
       '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류', '당사자종별피해자',
       '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류', '차량용도피해자_중분류',
       '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부', '어린이보호구역_여부',
       '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태', '노면상태_대분류', '노면상태',
       '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수', '부상신고자수', 'date', '빈도 수',
       '차대사람_기타', '차대사람_길가장자리구역통행중', '차대사람_보도통행중', '차대사람_횡단중', '차대차_기타',
       '차대차_정면충돌', '차대차_추돌', '차대차_측면충돌', '차대차_후진중충돌', '차도통행중', '차량단독_공작물충돌',
       '차량단독_기타', '차량단독_도로이탈', '차량단독_전도', '차량단독_전도전복', '차량단독_전복'],
      dtype='object')

In [68]:
df.drop(['사고유형_대분류','사고유형_중분류', '사고유형'], axis = 1, inplace = True)

In [69]:
df['성별가해자'].unique()

array(['기타불명', '남', '여'], dtype=object)

In [70]:
#가해자성별,피해자성별 : 순서변수 (여' : 1, '남' : 2, '기타불명', '없음' : 0)
mapping = {'여' : 1, '남' : 2, '기타불명': 0}
df['가해자성별'] = df['성별가해자'].map(mapping)

In [71]:
df.drop('성별가해자', axis = 1, inplace = True) #성별가해자 컬럼 제거

In [72]:
df['성별가해자_1'].unique()

array(['남', '여', '기타불명', '없음'], dtype=object)

In [73]:
#피해자성별
mapping = {'여' : 1, '남' : 2, '없음' : 0, '기타불명' : 0}
df['피해자성별'] = df['성별가해자_1'].map(mapping)

In [74]:
df.drop('성별가해자_1', axis = 1, inplace = True) #성별가해자_1(피해자 성별) 컬럼 제거

In [75]:
#연령변수 -> 범주화하여 전처리 
# 10대이하, 20, 30, 40, 50, 60, 70, 80, 90대이상

In [76]:
df['연령가해자'].unique()

array(['불명', '23세', '71세', '59세', '54세', '33세', '37세', '75세', '26세',
       '31세', '35세', '51세', '56세', '40세', '65세', '52세', '38세', '68세',
       '28세', '61세', '81세', '36세', '27세', '29세', '44세', '60세', '57세',
       '72세', '58세', '49세', '48세', '66세', '20세', '55세', '39세', '53세',
       '63세', '82세', '41세', '62세', '42세', '45세', '47세', '46세', '24세',
       '32세', '50세', '25세', '80세', '22세', '43세', '77세', '30세', '64세',
       '73세', '21세', '8세', '74세', '76세', '85세', '78세', '67세', '34세',
       '69세', '12세', '19세', '18세', '16세', '99세', '70세', '83세', '14세',
       '13세', '15세', '17세', '79세', '10세', '11세', '6세', '91세', '98세',
       '89세', '9세', '86세', '87세', '84세', '7세', '88세'], dtype=object)

In [77]:
age_gaheaja = []
for i in range(len(df['연령가해자'])):
    a = df['연령가해자'][i].split('세')[0]
    age_gaheaja.append(a)
df['age_gaheaja'] = age_gaheaja

In [78]:
df['age_gaheaja'].unique() #'불명' 값 처리가 필요

array(['불명', '23', '71', '59', '54', '33', '37', '75', '26', '31', '35',
       '51', '56', '40', '65', '52', '38', '68', '28', '61', '81', '36',
       '27', '29', '44', '60', '57', '72', '58', '49', '48', '66', '20',
       '55', '39', '53', '63', '82', '41', '62', '42', '45', '47', '46',
       '24', '32', '50', '25', '80', '22', '43', '77', '30', '64', '73',
       '21', '8', '74', '76', '85', '78', '67', '34', '69', '12', '19',
       '18', '16', '99', '70', '83', '14', '13', '15', '17', '79', '10',
       '11', '6', '91', '98', '89', '9', '86', '87', '84', '7', '88'],
      dtype=object)

In [79]:
df.loc[df['age_gaheaja'] == '불명', 'age_gaheaja'] = 0 #'불명' -> 0으로 바꿔줌.

In [80]:
df['age_gaheaja'] = df['age_gaheaja'].astype('int')
df['age_gaheaja'].unique()

array([ 0, 23, 71, 59, 54, 33, 37, 75, 26, 31, 35, 51, 56, 40, 65, 52, 38,
       68, 28, 61, 81, 36, 27, 29, 44, 60, 57, 72, 58, 49, 48, 66, 20, 55,
       39, 53, 63, 82, 41, 62, 42, 45, 47, 46, 24, 32, 50, 25, 80, 22, 43,
       77, 30, 64, 73, 21,  8, 74, 76, 85, 78, 67, 34, 69, 12, 19, 18, 16,
       99, 70, 83, 14, 13, 15, 17, 79, 10, 11,  6, 91, 98, 89,  9, 86, 87,
       84,  7, 88])

In [81]:
df.loc[df['age_gaheaja'] < 20, 'age_gaheaja'] = 10
df.loc[(df['age_gaheaja'] >= 20) & (df['age_gaheaja'] < 30), 'age_gaheaja'] = 20
df.loc[(df['age_gaheaja'] >= 30) & (df['age_gaheaja'] < 40), 'age_gaheaja'] = 30
df.loc[(df['age_gaheaja'] >= 40) & (df['age_gaheaja'] < 50), 'age_gaheaja'] = 40
df.loc[(df['age_gaheaja'] >= 50) & (df['age_gaheaja'] < 60), 'age_gaheaja'] = 50
df.loc[(df['age_gaheaja'] >= 60) & (df['age_gaheaja'] < 70), 'age_gaheaja'] = 60
df.loc[(df['age_gaheaja'] >= 70) & (df['age_gaheaja'] < 80), 'age_gaheaja'] = 70
df.loc[(df['age_gaheaja'] >= 80) & (df['age_gaheaja'] < 90), 'age_gaheaja'] = 80
df.loc[df['age_gaheaja'] > 90, 'age_gaheaja'] = 90

In [82]:
df['age_gaheaja'] = df['age_gaheaja'].astype('str')
df['age_gaheaja'] = df['age_gaheaja'] + '대'

In [83]:
df.loc[df['age_gaheaja'] == '10대','age_gaheaja'] = 1
df.loc[df['age_gaheaja'] == '20대','age_gaheaja'] = 2
df.loc[df['age_gaheaja'] == '30대','age_gaheaja'] = 3
df.loc[df['age_gaheaja'] == '40대','age_gaheaja'] = 4
df.loc[df['age_gaheaja'] == '50대','age_gaheaja'] = 5
df.loc[df['age_gaheaja'] == '60대','age_gaheaja'] = 6
df.loc[df['age_gaheaja'] == '70대','age_gaheaja'] = 7
df.loc[df['age_gaheaja'] == '80대','age_gaheaja'] = 8
df.loc[df['age_gaheaja'] == '90대','age_gaheaja'] = 9

In [84]:
df['age_gaheaja'].unique()

array([1, 2, 7, 5, 3, 4, 6, 8, 9], dtype=object)

In [85]:
df['연령피해자'].unique()

array(['74세', '33세', '9세', '30세', '12세', '7세', '58세', '80세', '10세', '42세',
       '71세', '48세', '44세', '81세', '38세', '54세', '50세', '63세', '51세',
       '65세', '67세', '13세', '79세', '46세', '72세', '31세', '21세', '85세',
       '34세', '11세', '49세', '24세', '22세', '52세', '36세', '69세', '41세',
       '64세', '8세', '15세', '60세', '29세', '53세', '91세', '70세', '82세',
       '56세', '59세', '20세', '76세', '28세', '16세', '83세', '75세', '62세',
       '68세', '73세', '77세', '39세', '26세', '78세', '19세', '43세', '35세',
       '32세', '61세', '55세', '66세', '17세', '45세', '27세', '23세', '25세',
       '37세', '18세', '89세', '57세', '86세', '14세', '40세', '47세', '6세',
       '88세', '84세', '87세', '98세', '90세', '5세', '불명', '없음'], dtype=object)

In [86]:
# 피해자연령 
# 10대이하, 20, 30, 40, 50, 60, 70, 80, 90대이상
age_piheaja = []
for i in range(len(df['연령피해자'])):
    a = df['연령피해자'][i].split('세')[0]
    age_piheaja.append(a)
df['age_piheaja'] = age_piheaja

In [87]:
df['age_piheaja'].unique()

array(['74', '33', '9', '30', '12', '7', '58', '80', '10', '42', '71',
       '48', '44', '81', '38', '54', '50', '63', '51', '65', '67', '13',
       '79', '46', '72', '31', '21', '85', '34', '11', '49', '24', '22',
       '52', '36', '69', '41', '64', '8', '15', '60', '29', '53', '91',
       '70', '82', '56', '59', '20', '76', '28', '16', '83', '75', '62',
       '68', '73', '77', '39', '26', '78', '19', '43', '35', '32', '61',
       '55', '66', '17', '45', '27', '23', '25', '37', '18', '89', '57',
       '86', '14', '40', '47', '6', '88', '84', '87', '98', '90', '5',
       '불명', '없음'], dtype=object)

In [88]:
df.loc[df['age_piheaja'] == '불명', 'age_piheaja'] = 0
df.loc[df['age_piheaja'] == '없음', 'age_piheaja'] = 0

In [89]:
# 문자 -> 숫자 변환
df['age_piheaja'] = df['age_piheaja'].astype('int')

In [90]:
df['age_piheaja'].unique()

array([74, 33,  9, 30, 12,  7, 58, 80, 10, 42, 71, 48, 44, 81, 38, 54, 50,
       63, 51, 65, 67, 13, 79, 46, 72, 31, 21, 85, 34, 11, 49, 24, 22, 52,
       36, 69, 41, 64,  8, 15, 60, 29, 53, 91, 70, 82, 56, 59, 20, 76, 28,
       16, 83, 75, 62, 68, 73, 77, 39, 26, 78, 19, 43, 35, 32, 61, 55, 66,
       17, 45, 27, 23, 25, 37, 18, 89, 57, 86, 14, 40, 47,  6, 88, 84, 87,
       98, 90,  5,  0])

In [91]:
# 숫자로 된 변수 범주화 
df.loc[(df['age_piheaja'] >= 1)  & (df['age_piheaja'] < 10), 'age_piheaja'] = 1
df.loc[(df['age_piheaja'] >= 10) & (df['age_piheaja'] < 20), 'age_piheaja'] = 2
df.loc[(df['age_piheaja'] >= 20) & (df['age_piheaja'] < 30), 'age_piheaja'] = 3
df.loc[(df['age_piheaja'] >= 30) & (df['age_piheaja'] < 40), 'age_piheaja'] = 4
df.loc[(df['age_piheaja'] >= 40) & (df['age_piheaja'] < 50), 'age_piheaja'] = 5
df.loc[(df['age_piheaja'] >= 50) & (df['age_piheaja'] < 60), 'age_piheaja'] = 6
df.loc[(df['age_piheaja'] >= 60) & (df['age_piheaja'] < 70), 'age_piheaja'] = 7
df.loc[(df['age_piheaja'] >= 70) & (df['age_piheaja'] < 80), 'age_piheaja'] = 8
df.loc[(df['age_piheaja'] >= 80) & (df['age_piheaja'] < 90), 'age_piheaja'] = 9
df.loc[df['age_piheaja'] >= 90, 'age_piheaja'] = 10

In [92]:
df['age_piheaja'].unique()

array([7, 3, 0, 1, 5, 8, 4, 6, 2, 9])

In [93]:
df.columns

Index(['index', 'TAAS사고관리번호', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자',
       '보호장구가해자_대분류', '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자',
       '행동유형가해자_대분류', '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자',
       '가해자신체상해주부위', '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류',
       '당사자종별피해자', '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류',
       '차량용도피해자_중분류', '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부',
       '어린이보호구역_여부', '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태',
       '노면상태_대분류', '노면상태', '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수',
       '부상신고자수', 'date', '빈도 수', '차대사람_기타', '차대사람_길가장자리구역통행중', '차대사람_보도통행중',
       '차대사람_횡단중', '차대차_기타', '차대차_정면충돌', '차대차_추돌', '차대차_측면충돌', '차대차_후진중충돌',
       '차도통행중', '차량단독_공작물충돌', '차량단독_기타', '차량단독_도로이탈', '차량단독_전도', '차량단독_전도전복',
       '차량단독_전복', '가해자성별', '피해자성별', 'age_gaheaja', 'age_piheaja'],
      dtype='object')

In [94]:
df['연령가해자'] = df['age_gaheaja']
df['연령피해자'] = df['age_piheaja']

In [95]:
df.drop(['age_gaheaja','age_piheaja'], axis = 1, inplace = True) #age_gaheaja,age_piheaja 두 컬럼 제거

In [96]:
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,차대차_후진중충돌,차도통행중,차량단독_공작물충돌,차량단독_기타,차량단독_도로이탈,차량단독_전도,차량단독_전도전복,차량단독_전복,가해자성별,피해자성별
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,0,0,0,0,0,0,2
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,0,0,0,0,0,2,2
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,0,0,0,0,0,0,2,1
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,0,0,0,0,2,2
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,0,0,0,0,0,2,2
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,0,0,0,0,1,2
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,0,0,0,0,2,2
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,0,0,0,0,1,2
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,0,0,0,0,0,2,2

In [97]:
df.columns

Index(['index', 'TAAS사고관리번호', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '연령가해자', '연령피해자', '음주측정수치가해자_대분류', '음주측정수치가해자',
       '보호장구가해자_대분류', '보호장구가해자', '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자',
       '행동유형가해자_대분류', '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자',
       '가해자신체상해주부위', '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류',
       '당사자종별피해자', '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류',
       '차량용도피해자_중분류', '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부',
       '어린이보호구역_여부', '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태',
       '노면상태_대분류', '노면상태', '교차로형태_대분류', '교차로형태', '사망자수', '중상자수', '경상자수',
       '부상신고자수', 'date', '빈도 수', '차대사람_기타', '차대사람_길가장자리구역통행중', '차대사람_보도통행중',
       '차대사람_횡단중', '차대차_기타', '차대차_정면충돌', '차대차_추돌', '차대차_측면충돌', '차대차_후진중충돌',
       '차도통행중', '차량단독_공작물충돌', '차량단독_기타', '차량단독_도로이탈', '차량단독_전도', '차량단독_전도전복',
       '차량단독_전복', '가해자성별', '피해자성별'],
      dtype='object')

In [98]:
print(df['음주측정수치가해자_대분류'].unique()) #확실히 음주 상태인 것을 1, 아닌 것을 0으로 mapping
mapping = {'기타불명'  : 0,
           '해당 없음' : 0, 
           '측정불능'  : 0, 
           '음주운전'  : 1,
           '음주상태'  : 1}
df['음주측정수치가해자_대분류'] = df['음주측정수치가해자_대분류'].map(mapping)
df['음주측정수치가해자_대분류']

['기타불명' '해당 없음' '음주운전' '음주상태' '측정불능']

0       0
1       0
2       0
3       0
4       0
       ..
1818    0
1819    0
1820    1
1821    0
1822    0
Name: 음주측정수치가해자_대분류, Length: 1823, dtype: int64

In [99]:
df['음주측정수치가해자_대분류'].unique()

array([0, 1], dtype=int64)

In [100]:
df['음주측정수치가해자'] = df['음주측정수치가해자_대분류'] #음주측정수치가해자_대분류 -> 음주측정수치가해자 로 넣어줌
df['음주측정수치가해자']

0       0
1       0
2       0
3       0
4       0
       ..
1818    0
1819    0
1820    1
1821    0
1822    0
Name: 음주측정수치가해자, Length: 1823, dtype: int64

In [101]:
df.drop('음주측정수치가해자_대분류', axis = 1, inplace = True) # 음주측정수치가해자_대분류 컬럼 제거

In [102]:
df.columns

Index(['index', 'TAAS사고관리번호', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '연령가해자', '연령피해자', '음주측정수치가해자', '보호장구가해자_대분류', '보호장구가해자',
       '보호장구피해자_대분류', '보호장구피해자', '법규위반가해자', '행동유형가해자_대분류', '행동유형가해자_중분류',
       '행동유형가해자', '신체상해정도가해자', '신체상해정도피해자', '가해자신체상해주부위', '피해자신체상해주부위',
       '당사자종별가해자_대분류', '당사자종별가해자', '당사자종별피해자_대분류', '당사자종별피해자', '차량용도가해자_대분류',
       '차량용도가해자_중분류', '차량용도가해자', '차량용도피해자_대분류', '차량용도피해자_중분류', '차량용도피해자',
       '도로종류', '도로형태_대분류', '도로형태', '노인보호구역_여부', '어린이보호구역_여부', '자전거도로_여부',
       '도로선형_대분류', '도로선형_중분류', '도로선형', '기상상태', '노면상태_대분류', '노면상태', '교차로형태_대분류',
       '교차로형태', '사망자수', '중상자수', '경상자수', '부상신고자수', 'date', '빈도 수', '차대사람_기타',
       '차대사람_길가장자리구역통행중', '차대사람_보도통행중', '차대사람_횡단중', '차대차_기타', '차대차_정면충돌',
       '차대차_추돌', '차대차_측면충돌', '차대차_후진중충돌', '차도통행중', '차량단독_공작물충돌', '차량단독_기타',
       '차량단독_도로이탈', '차량단독_전도', '차량단독_전도전복', '차량단독_전복', '가해자성별', '피해자성별'],
      dtype='object')

In [103]:
df['보호장구가해자_대분류'].unique()

array(['기타불명', '안전벨트/카시트', '안전모'], dtype=object)

In [104]:
pd.DataFrame(df.groupby(['보호장구가해자_대분류','보호장구가해자'])['빈도 수'].count())

                     빈도 수
보호장구가해자_대분류 보호장구가해자
기타불명        기타불명      350
안전모         미착용       273
            착용        146
            착용불명       59
안전벨트/카시트    미착용        11
            착용        786
            착용불명      198

In [105]:
df.loc[(df['보호장구가해자'] == '기타불명'), '보호장구가해자'] = '가해자_보호장구_기타불명'
df.loc[(df['보호장구가해자_대분류'] == '안전모')&(df['보호장구가해자'] == '미착용'),'보호장구가해자'] = '가해자_안전모_미착용'
df.loc[(df['보호장구가해자_대분류'] == '안전모')&(df['보호장구가해자'] == '착용'), '보호장구가해자'] = '가해자_안전모_착용'
df.loc[(df['보호장구가해자_대분류'] == '안전모')&(df['보호장구가해자'] == '착용불명'),'보호장구가해자'] = '가해자_안전모_착용불명' 
df.loc[(df['보호장구가해자_대분류'] == '안전벨트/카시트')&(df['보호장구가해자'] == '미착용'),'보호장구가해자'] = '가해자_안전벨트/카시트_미착용'
df.loc[(df['보호장구가해자_대분류'] == '안전벨트/카시트')&(df['보호장구가해자'] == '착용'),'보호장구가해자'] = '가해자_안전벨트/카시트_착용'
df.loc[(df['보호장구가해자_대분류'] == '안전벨트/카시트')&(df['보호장구가해자'] == '착용불명'),'보호장구가해자'] = '가해자_안전벨트/카시트_착용불명'

In [106]:
df['보호장구가해자'].unique()

array(['가해자_보호장구_기타불명', '가해자_안전벨트/카시트_착용불명', '가해자_안전벨트/카시트_착용',
       '가해자_안전모_착용', '가해자_안전벨트/카시트_미착용', '가해자_안전모_미착용', '가해자_안전모_착용불명'],
      dtype=object)

In [107]:
보호장구가해자_dummies = pd.get_dummies(df['보호장구가해자'])
보호장구가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 보호장구가해자_dummies, how = 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,차량단독_전복,가해자성별,피해자성별,가해자_보호장구_기타불명,가해자_안전모_미착용,가해자_안전모_착용,가해자_안전모_착용불명,가해자_안전벨트/카시트_미착용,가해자_안전벨트/카시트_착용,가해자_안전벨트/카시트_착용불명
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,2,1,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,2,2,1,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,2,1,0,0,0,0,0,0,1
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,2,2,0,0,0,0,0,1,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,2,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,2,2,1,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,1,2,0,0,0,0,0,1,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,2,2,0,0,0,0,0,1,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,1,2,0,0,0,0,0,1,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,2,2,1,0,0,0,0,0,0

In [108]:
df.drop(['보호장구가해자_대분류','보호장구가해자'], axis = 1, inplace = True)

In [109]:
df.columns

Index(['index', 'TAAS사고관리번호', '발생지_시도', '발생지_시군구', 'X_POINT', 'Y_POINT', '요일',
       '주야', '사고내용', '연령가해자', '연령피해자', '음주측정수치가해자', '보호장구피해자_대분류', '보호장구피해자',
       '법규위반가해자', '행동유형가해자_대분류', '행동유형가해자_중분류', '행동유형가해자', '신체상해정도가해자',
       '신체상해정도피해자', '가해자신체상해주부위', '피해자신체상해주부위', '당사자종별가해자_대분류', '당사자종별가해자',
       '당사자종별피해자_대분류', '당사자종별피해자', '차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자',
       '차량용도피해자_대분류', '차량용도피해자_중분류', '차량용도피해자', '도로종류', '도로형태_대분류', '도로형태',
       '노인보호구역_여부', '어린이보호구역_여부', '자전거도로_여부', '도로선형_대분류', '도로선형_중분류', '도로선형',
       '기상상태', '노면상태_대분류', '노면상태', '교차로형태_대분류', '교차로형태', '사망자수', '중상자수',
       '경상자수', '부상신고자수', 'date', '빈도 수', '차대사람_기타', '차대사람_길가장자리구역통행중',
       '차대사람_보도통행중', '차대사람_횡단중', '차대차_기타', '차대차_정면충돌', '차대차_추돌', '차대차_측면충돌',
       '차대차_후진중충돌', '차도통행중', '차량단독_공작물충돌', '차량단독_기타', '차량단독_도로이탈', '차량단독_전도',
       '차량단독_전도전복', '차량단독_전복', '가해자성별', '피해자성별', '가해자_보호장구_기타불명',
       '가해자_안전모_미착용', '가해자_안전모_착용', '가해자_안전모_착용불명', '가해자_안전벨트/카시트_미착용',
       '가해자_안전벨트/카시트_착용', '가해자_안전벨트/카시트_착용불명'],
      dtype='object')

In [110]:
df['보호장구피해자'].unique()

array(['기타불명', '미착용', '착용', '착용불명', '보행자', '없음'], dtype=object)

In [111]:
pd.DataFrame(df.groupby(['보호장구피해자_대분류','보호장구피해자'])['빈도 수'].count())

                     빈도 수
보호장구피해자_대분류 보호장구피해자
기타불명        기타불명      323
보행자         보행자        82
안전모         미착용       557
            착용        398
            착용불명      145
안전벨트/카시트    미착용         2
            착용        219
            착용불명       68
없음          없음         29

In [112]:
df.loc[(df['보호장구피해자'] == '기타불명'), '보호장구피해자'] = '피해자_보호장구_기타불명'
df.loc[(df['보호장구피해자'] == '보행자'), '보호장구피해자'] = '피해자_보호장구_보행자'
df.loc[(df['보호장구피해자'] == '없음'), '보호장구피해자'] = '피해자_보호장구_없음'
df.loc[(df['보호장구피해자_대분류'] == '안전모')&(df['보호장구피해자'] == '미착용'),'보호장구피해자'] = '피해자_안전모_미착용'
df.loc[(df['보호장구피해자_대분류'] == '안전모')&(df['보호장구피해자'] == '착용'), '보호장구피해자'] = '피해자_안전모_착용'
df.loc[(df['보호장구피해자_대분류'] == '안전모')&(df['보호장구피해자'] == '착용불명'),'보호장구피해자'] = '피해자_안전모_착용불명' 
df.loc[(df['보호장구피해자_대분류'] == '안전벨트/카시트')&(df['보호장구피해자'] == '미착용'),'보호장구피해자'] = '피해자_안전벨트/카시트_미착용'
df.loc[(df['보호장구피해자_대분류'] == '안전벨트/카시트')&(df['보호장구피해자'] == '착용'),'보호장구피해자'] = '피해자_안전벨트/카시트_착용'
df.loc[(df['보호장구피해자_대분류'] == '안전벨트/카시트')&(df['보호장구피해자'] == '착용불명'),'보호장구피해자'] = '피해자_안전벨트/카시트_착용불명'

In [113]:
보호장구피해자_dummies = pd.get_dummies(df['보호장구피해자'])
보호장구피해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 보호장구피해자_dummies, how = 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,가해자_안전벨트/카시트_착용불명,피해자_보호장구_기타불명,피해자_보호장구_보행자,피해자_보호장구_없음,피해자_안전모_미착용,피해자_안전모_착용,피해자_안전모_착용불명,피해자_안전벨트/카시트_미착용,피해자_안전벨트/카시트_착용,피해자_안전벨트/카시트_착용불명
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,1,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,0,1,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,1,0,0,0,0,1,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,1,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,1,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,1,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,1,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,1,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,0,1,0,0,0,0,0

In [114]:
df.drop(['보호장구피해자_대분류','보호장구피해자'], axis = 1,inplace = True)

In [115]:
df['법규위반가해자'].unique()

array(['안전운전 의무 불이행', '신호위반', '교차로 통행방법 위반', '기타', '안전거리 미확보', '중앙선 침범',
       '과속', '보행자 보호의무 위반'], dtype=object)

In [116]:
#법규위반가해자 : 더미 변수 생성 (법가 + 세부항목) 후 컬럼 제거
df['법규위반가해자'] = '법가' + '_' + df['법규위반가해자']
법규위반가해자_dummies = pd.get_dummies(df['법규위반가해자'])
법규위반가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 법규위반가해자_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,피해자_안전벨트/카시트_착용,피해자_안전벨트/카시트_착용불명,법가_과속,법가_교차로 통행방법 위반,법가_기타,법가_보행자 보호의무 위반,법가_신호위반,법가_안전거리 미확보,법가_안전운전 의무 불이행,법가_중앙선 침범
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,0,0,0,0,0,1,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,0,0,0,0,0,1,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,0,0,0,0,0,0,1,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,0,0,0,0,1,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,0,0,0,0,1,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,0,0,0,0,1,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,0,0,0,0,1,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,0,0,0,0,1,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,0,0,0,1,0,0,0

In [117]:
df.drop('법규위반가해자', axis = 1, inplace = True) #법규위반가해자 컬럼 제거

* 행동유형가해자_대분류, 행동유형가해자_중분류, 행동유형가해자 에서 '행동유형가해자' 만 살리기로 함

In [118]:
df['행동유형가해자_대분류'].unique()

array(['불명', '운전자'], dtype=object)

In [119]:
df['행동유형가해자_중분류'].unique()

array(['불명', '회전관련', '직진관련', '주정차중', '후진 중', '기타', '자동차 등', '주행 중 대기'],
      dtype=object)

In [120]:
df['행동유형가해자'].unique()

array(['불명', '우회전 중', '직진 중', '좌회전 중', '진로변경 중', '앞지르기 중', '주정차중', '후진 중',
       '기타', '좌우회전중', 'U턴 중', '직진중', 'U턴중', '후진중', '주ㆍ정차중 ', '진로변경중',
       '앞지르기중', '주행 중 대기', '출발중'], dtype=object)

In [121]:
pd.DataFrame(df['행동유형가해자'].value_counts())

         행동유형가해자
직진 중         716
우회전 중        256
좌회전 중        188
직진중          167
좌우회전중        152
기타            99
진로변경 중        57
불명            44
후진 중          28
진로변경중         23
U턴 중          21
주정차중          15
U턴중           13
앞지르기 중        11
후진중           10
주ㆍ정차중          9
주행 중 대기        7
출발중            4
앞지르기중          3

In [122]:
df.loc[(df['행동유형가해자'] == '직진 중'), '행동유형가해자'] = '가해자_행동_직진중'
df.loc[(df['행동유형가해자'] == '우회전 중'), '행동유형가해자'] = '가해자_행동_우회전중'
df.loc[(df['행동유형가해자'] == '좌회전 중'), '행동유형가해자'] = '가해자_행동_좌회전중'
df.loc[(df['행동유형가해자'] == '직진중'), '행동유형가해자'] = '가해자_행동_직진중'
df.loc[(df['행동유형가해자'] == '좌우회전중'), '행동유형가해자'] = '가해자_행동_좌우회전중'
df.loc[(df['행동유형가해자'] == '기타'), '행동유형가해자'] = '가해자_행동_기타'
df.loc[(df['행동유형가해자'] == '진로변경 중'), '행동유형가해자'] = '가해자_행동_진로변경중'
df.loc[(df['행동유형가해자'] == '불명'), '행동유형가해자'] = '가해자_행동_불명'
df.loc[(df['행동유형가해자'] == '후진 중'), '행동유형가해자'] = '가해자_행동_후진중'
df.loc[(df['행동유형가해자'] == '진로변경중'), '행동유형가해자'] = '가해자_행동_진로변경중'
df.loc[(df['행동유형가해자'] == 'U턴 중'), '행동유형가해자'] = '가해자_행동_U턴중'
df.loc[(df['행동유형가해자'] == '주정차중'), '행동유형가해자'] = '가해자_행동_주정차중'
df.loc[(df['행동유형가해자'] == 'U턴중'), '행동유형가해자'] ='가해자_행동_U턴중'
df.loc[(df['행동유형가해자'] == '앞지르기 중'), '행동유형가해자'] = '가해자_행동_앞지르기중'
df.loc[(df['행동유형가해자'] == '후진중'), '행동유형가해자'] ='가해자_행동_후진중'
df.loc[(df['행동유형가해자'] == '주ㆍ정차중 '), '행동유형가해자'] = '가해자_행동_주정차중'
df.loc[(df['행동유형가해자'] == '주행 중 대기'), '행동유형가해자'] = '가해자_행동_주행중대기'
df.loc[(df['행동유형가해자'] == '출발중'), '행동유형가해자'] = '가해자_행동_출발중'
df.loc[(df['행동유형가해자'] == '앞지르기중'), '행동유형가해자'] = '가해자_행동_앞지르기중'

In [123]:
행동유형가해자_dummies = pd.get_dummies(df['행동유형가해자'])
행동유형가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 행동유형가해자_dummies, on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,가해자_행동_앞지르기중,가해자_행동_우회전중,가해자_행동_좌우회전중,가해자_행동_좌회전중,가해자_행동_주정차중,가해자_행동_주행중대기,가해자_행동_직진중,가해자_행동_진로변경중,가해자_행동_출발중,가해자_행동_후진중
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,1,0,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,1,0,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,0,1,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,1,0,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,1,0,0,0,0,0,0,0

In [124]:
df.drop(['행동유형가해자_대분류','행동유형가해자_중분류','행동유형가해자'], axis = 1, inplace = True)

* 신체상해정도가해자, 신체상해정도피해자 : 생략 / 이전 전처리때 생략하였음 (컬럼 삭제)

In [125]:
df['신체상해정도가해자'].unique()

array(['기타불명', '상해없음', '경상', '부상신고', '중상', '사망'], dtype=object)

In [126]:
df['신체상해정도피해자'].unique()

array(['경상', '부상신고', '중상', '상해없음', '사망', '기타불명', '없음'], dtype=object)

In [127]:
df.drop(['신체상해정도가해자','신체상해정도피해자'], axis = 1, inplace = True)

In [128]:
df['가해자신체상해주부위'].unique()

array(['상해없음', '손', '앞목', '기타', '뒷목', '허리', '얼굴', '팔', '발', '가슴', '어깨',
       '하퇴부', '목', '머리', '대퇴부', '배', '불명'], dtype=object)

In [129]:
df['피해자신체상해주부위'].unique()

array(['하퇴부', '팔', '허리', '기타', '상해없음', '머리', '발', '대퇴부', '가슴', '손', '얼굴',
       '뒷목', '어깨', '배', '목', '불명', '앞목', '등', '없음'], dtype=object)

In [130]:
#가해자신체상해주부위, 피해자신체상해주부위 : 더미변수 생성 (가 + 신체부위 컬럼) 후 컬럼 제거
df['가해자신체상해주부위'] = '가' + '_' + df['가해자신체상해주부위'] 
df_가해자신체상해주부위_dummies = pd.get_dummies(data = df['가해자신체상해주부위'])
df_가해자신체상해주부위_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호'] 
df = pd.merge(df, df_가해자신체상해주부위_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,가_배,가_불명,가_상해없음,가_손,가_앞목,가_어깨,가_얼굴,가_팔,가_하퇴부,가_허리
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,1,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,1,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,1,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,1,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,1,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,1,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,1,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,1,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,1,0,0,0,0,0,0,0

In [131]:
df.drop('가해자신체상해주부위', axis = 1, inplace = True)

In [132]:
df['피해자신체상해주부위'] = '피' + '_' + df['피해자신체상해주부위']
df_피해자신체상해주부위_dummies = pd.get_dummies(data = df['피해자신체상해주부위'])
df_피해자신체상해주부위_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_피해자신체상해주부위_dummies, how= 'outer', on = 'TAAS사고관리번호')

In [133]:
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,피_불명,피_상해없음,피_손,피_앞목,피_어깨,피_얼굴,피_없음,피_팔,피_하퇴부,피_허리
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,0,0,0,0,0,1,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,0,0,0,0,1,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,0,0,0,0,0,0,0,1
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,0,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,1,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,1,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,0,0,0,0,0,1
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,0,0,0,0,0,0,0

In [134]:
df.drop('피해자신체상해주부위', axis = 1, inplace = True)

* 당사자종별가해자_대분류 컬럼의 속성을 살려서, 더미변수화

In [135]:
#당사자종별가해자_대분류
df['당사자종별가해자_대분류'].unique()

array(['불명', '승용차', '화물차', '자전거', '원동기장치자전거', '승합차', '이륜차', '건설기계', '특수차',
       '사륜오토바이(ATV)', '개인형이동수단(PM)', '기타'], dtype=object)

In [136]:
pd.DataFrame(df.groupby(['당사자종별가해자_대분류','당사자종별가해자'])['빈도 수'].count())

                          빈도 수
당사자종별가해자_대분류 당사자종별가해자
개인형이동수단(PM)  개인형이동수단(PM)    46
건설기계         건설기계           10
기타           기타              1
불명           불명             36
사륜오토바이(ATV)  사륜오토바이(ATV)     2
승용차          경형             97
             대형              3
             소형             21
             승용차           739
             중형             94
승합차          경형              4
             대형              2
             소형              5
             승합차            45
             중형              2
원동기장치자전거     원동기장치자전거       20
이륜차          소형             12
             이륜차            39
자전거          자전거           486
특수차          특수차             4
화물차          경형              1
             대형              1
             소형             24
             중형              1
             화물차           128

In [137]:
df['당사자종별가해자_대분류'] = '당종가' + '_' + df['당사자종별가해자_대분류']
df_당사자종별가해자_dummies = pd.get_dummies(data = df['당사자종별가해자_대분류'])
df_당사자종별가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_당사자종별가해자_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,당종가_기타,당종가_불명,당종가_사륜오토바이(ATV),당종가_승용차,당종가_승합차,당종가_원동기장치자전거,당종가_이륜차,당종가_자전거,당종가_특수차,당종가_화물차
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,1,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,1,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,0,1,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,0,0,0,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,1,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,1,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,0,0,0,0,0,1
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,1,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,1,0,0,0,0,0,0

In [138]:
df.drop('당사자종별가해자', axis  = 1, inplace = True)

In [139]:
df.drop('당사자종별가해자_대분류', axis = 1, inplace = True)

* 당사자종별피해자_대분류 컬럼의 속성을 살려서, 더미변수화

In [140]:
pd.DataFrame(df.groupby(['당사자종별피해자_대분류','당사자종별피해자'])['빈도 수'].count())

                          빈도 수
당사자종별피해자_대분류 당사자종별피해자
개인형이동수단(PM)  개인형이동수단(PM)    50
건설기계         건설기계            2
보행자          보행자            82
불명           불명              6
승용차          경형             30
             대형              1
             소형              2
             승용차           227
             중형             25
승합차          대형              1
             소형              2
             승합차            18
             중형              1
없음           없음             29
원동기장치자전거     원동기장치자전거      311
이륜차          소형              5
             이륜차            19
자전거          자전거           975
특수차          경형              2
             특수차             2
화물차          소형              4
             화물차            29

In [141]:
len(df['당사자종별피해자_대분류'].unique())

12

In [142]:
df['당사자종별피해자_대분류'] = '당종피' + '_' + df['당사자종별피해자_대분류']
df_당사자종별피해자_dummies = pd.get_dummies(data = df['당사자종별피해자_대분류'])
df_당사자종별피해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_당사자종별피해자_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,당종피_보행자,당종피_불명,당종피_승용차,당종피_승합차,당종피_없음,당종피_원동기장치자전거,당종피_이륜차,당종피_자전거,당종피_특수차,당종피_화물차
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,0,0,0,0,1,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,0,0,0,0,1,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,0,0,0,0,0,1,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,0,0,0,1,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,0,0,0,0,0,0,0

In [143]:
df.drop(['당사자종별피해자','당사자종별피해자_대분류'], axis = 1, inplace = True)

* 차량용도가해자_대분류, 차량용도가해자_중분류, 차량용도가해자 -  중분류 속성만 살려서 더미변수화
* 사업용/비사업용 구분 없이 묶어버리기 - 결론 : 중분류만 살려서 더미변수화
* 버스종류는 버스로 묶기

In [144]:
pd.DataFrame(df.groupby(['차량용도가해자_대분류', '차량용도가해자_중분류', '차량용도가해자'])['빈도 수'].count())

                                     빈도 수
차량용도가해자_대분류 차량용도가해자_중분류 차량용도가해자
개인형이동수단(PM) 개인형이동수단(PM) 개인형이동수단(PM)    46
기타          기타          기타              1
기타불명        기타불명        기타/불명          11
불명          불명          불명             25
비사업용        기타/건설기계     기타/건설기계        10
            버스          버스             19
            비사업용기타      비사업용기타          7
            승용차         승용차           780
            어린이통학버스     어린이통학버스         7
            화물차         화물차           131
사륜오토바이(ATV) 사륜오토바이(ATV) 사륜오토바이(ATV)     2
사업용         기타/건설기계     기타/건설기계        12
            노선버스        고속버스            1
                        시내버스            8
            렌터카         렌터카            42
            전세버스        전세버스            5
            택시          개인택시           38
                        법인택시           94
            화물차         일반화물            3
                        화물차            24
원동기장치자전거    원동기장치자전거    원동기장치자전거       20
이륜차         이륜차         이륜차            51
자전거         자전거         자전거           486

In [145]:
df['차량용도가해자_중분류'].unique()

array(['불명', '승용차', '렌터카', '화물차', '자전거', '원동기장치자전거', '택시', '버스', '이륜차',
       '기타/건설기계', '기타불명', '노선버스', '전세버스', '비사업용기타', '어린이통학버스',
       '사륜오토바이(ATV)', '개인형이동수단(PM)', '기타'], dtype=object)

* 버스 : 버스, 노선버스, 전세버스
* 기타 : 불명, 기타/건설기계, 기타불명, 비사업용기타, 기타
* 자전거 : 원동기장치자전거, 자전거

In [146]:
df.loc[(df['차량용도가해자_중분류'] == '불명'), '차량용도가해자'] = '가해자_차량용도_불명'
df.loc[(df['차량용도가해자_중분류'] == '승용차'), '차량용도가해자'] = '가해자_차량용도_승용차'
df.loc[(df['차량용도가해자_중분류'] == '렌터카'), '차량용도가해자'] = '가해자_차량용도_렌터카'
df.loc[(df['차량용도가해자_중분류'] == '화물차'), '차량용도가해자'] = '가해자_차량용도_화물차'
df.loc[(df['차량용도가해자_중분류'] == '자전거'), '차량용도가해자'] = '가해자_차량용도_자전거'
df.loc[(df['차량용도가해자_중분류'] == '원동기장치자전거'), '차량용도가해자'] = '가해자_차량용도_자전거'
df.loc[(df['차량용도가해자_중분류'] == '택시'), '차량용도가해자'] = '가해자_차량용도_택시'
df.loc[(df['차량용도가해자_중분류'] == '버스'), '차량용도가해자'] = '가해자_차량용도_버스'
df.loc[(df['차량용도가해자_중분류'] == '이륜차'), '차량용도가해자'] = '가해자_차량용도_이륜차'
df.loc[(df['차량용도가해자_중분류'] == '기타/건설기계'), '차량용도가해자'] = '가해자_차량용도_기타'
df.loc[(df['차량용도가해자_중분류'] == '기타불명'), '차량용도가해자'] = '가해자_차량용도_기타'
df.loc[(df['차량용도가해자_중분류'] == '노선버스'), '차량용도가해자'] = '가해자_차량용도_버스'
df.loc[(df['차량용도가해자_중분류'] == '전세버스'), '차량용도가해자'] = '가해자_차량용도_버스'
df.loc[(df['차량용도가해자_중분류'] == '비사업용기타'), '차량용도가해자'] = '가해자_차량용도_기타'
df.loc[(df['차량용도가해자_중분류'] == '어린이통학버스'), '차량용도가해자'] = '가해자_차량용도_버스'
df.loc[(df['차량용도가해자_중분류'] == '사륜오토바이(ATV)'), '차량용도가해자'] = '가해자_차량용도_사륜오토바이'
df.loc[(df['차량용도가해자_중분류'] == '개인형이동수단(PM)'), '차량용도가해자'] = '가해자_차량용도_PM'
df.loc[(df['차량용도가해자_중분류'] == '기타'), '차량용도가해자'] = '가해자_차량용도_기타'

In [147]:
df['차량용도가해자'].unique()

array(['가해자_차량용도_불명', '가해자_차량용도_승용차', '가해자_차량용도_렌터카', '가해자_차량용도_화물차',
       '가해자_차량용도_자전거', '가해자_차량용도_택시', '가해자_차량용도_버스', '가해자_차량용도_이륜차',
       '가해자_차량용도_기타', '가해자_차량용도_사륜오토바이', '가해자_차량용도_PM'], dtype=object)

In [148]:
df_차량용도가해자_dummies = pd.get_dummies(data = df['차량용도가해자'])
df_차량용도가해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_차량용도가해자_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,가해자_차량용도_기타,가해자_차량용도_렌터카,가해자_차량용도_버스,가해자_차량용도_불명,가해자_차량용도_사륜오토바이,가해자_차량용도_승용차,가해자_차량용도_이륜차,가해자_차량용도_자전거,가해자_차량용도_택시,가해자_차량용도_화물차
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,1,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,0,0,1,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,1,0,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,0,0,0,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,0,0,0,0,0,1,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,0,0,0,0,1,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,0,0,0,0,0,1
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,0,1,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,0,0,1,0,0,0,0

In [149]:
df.drop(['차량용도가해자_대분류','차량용도가해자_중분류','차량용도가해자'], axis = 1, inplace = True)

* 차량용도피해자_대분류, 차량용도피해자_중분류, 차량용도피해자 - 중분류 속성만 살려서 더미변수화
* 사업용/비사업용 구분 없이 묶어버리기 - 결론 : 중분류만 살려서 더미변수화
* 버스종류는 버스로 묶기

In [150]:
#차량용도피해자
pd.DataFrame(df.groupby(['차량용도피해자_대분류', '차량용도피해자_중분류', '차량용도피해자'])['빈도 수'].count())

                                     빈도 수
차량용도피해자_대분류 차량용도피해자_중분류 차량용도피해자
개인형이동수단(PM) 개인형이동수단(PM) 개인형이동수단(PM)    50
기타불명        기타불명        기타/불명           3
보행자         보행자         보행자            82
불명          불명          불명              3
비사업용        기타/건설기계     기타/건설기계         3
            버스          버스              6
            비사업용기타      비사업용기타          4
            승용차         승용차           231
            어린이통학버스     어린이통학버스         1
            화물차         화물차            25
사업용         노선버스        시내버스            6
            렌터카         렌터카            15
            사업용기타       기타              3
            전세버스        전세버스            5
            콘크리트믹서      콘크리트믹서          1
            택시          개인택시           16
                        법인택시           22
            화물차         일반화물            1
                        화물차             7
없음          없음          없음             29
원동기장치자전거    원동기장치자전거    원동기장치자전거      311
이륜차         이륜차         이륜차            24
자전거         자전거         자전거           975

In [151]:
df['차량용도피해자'].unique()

array(['자전거', '원동기장치자전거', '개인택시', '화물차', '보행자', '기타/불명', '렌터카', '비사업용기타',
       '승용차', '이륜차', '기타', '법인택시', '없음', '버스', '일반화물', '전세버스', '콘크리트믹서',
       '기타/건설기계', '시내버스', '개인형이동수단(PM)', '어린이통학버스', '불명'], dtype=object)

* 버스 : 버스, 노선버스, 전세버스, 어린이통학버스
* 기타 : 불명, 기타/건설기계, 기타불명, 비사업용기타, 사업용기타, 없음
* 자전거 : 원동기장치자전거, 자전거

In [152]:
df.loc[(df['차량용도피해자_중분류'] == '자전거'), '차량용도피해자'] = '피해자_차량용도_자전거'
df.loc[(df['차량용도피해자_중분류'] == '원동기장치자전거'), '차량용도피해자'] = '피해자_차량용도_자전거'
df.loc[(df['차량용도피해자_중분류'] == '택시'), '차량용도피해자'] = '피해자_차량용도_택시'
df.loc[(df['차량용도피해자_중분류'] == '화물차'), '차량용도피해자'] = '피해자_차량용도_화물차'
df.loc[(df['차량용도피해자_중분류'] == '보행자'), '차량용도피해자'] = '피해자_차량용도_보행자'
df.loc[(df['차량용도피해자_중분류'] == '기타불명'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '렌터카'), '차량용도피해자'] = '피해자_차량용도_렌터카'
df.loc[(df['차량용도피해자_중분류'] == '비사업용기타'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '승용차'), '차량용도피해자'] = '피해자_차량용도_승용차'
df.loc[(df['차량용도피해자_중분류'] == '이륜차'), '차량용도피해자'] = '피해자_차량용도_이륜차'
df.loc[(df['차량용도피해자_중분류'] == '사업용기타'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '없음'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '버스'), '차량용도피해자'] = '피해자_차량용도_버스'
df.loc[(df['차량용도피해자_중분류'] == '전세버스'), '차량용도피해자'] = '피해자_차량용도_버스'
df.loc[(df['차량용도피해자_중분류'] == '콘크리트믹서'), '차량용도피해자'] = '피해자_차량용도_콘크리트믹서'
df.loc[(df['차량용도피해자_중분류'] == '기타/건설기계'), '차량용도피해자'] = '피해자_차량용도_기타'
df.loc[(df['차량용도피해자_중분류'] == '노선버스'), '차량용도피해자'] = '피해자_차량용도_버스'
df.loc[(df['차량용도피해자_중분류'] == '개인용이동수단(PM)'), '차량용도피해자'] = '피해자_차량용도_PM'
df.loc[(df['차량용도피해자_중분류'] == '어린이통학버스'), '차량용도피해자'] = '피해자_차량용도_버스'
df.loc[(df['차량용도피해자_중분류'] == '불명'), '차량용도피해자'] = '피해자_차량용도_기타'

In [153]:
df_차량용도피해자_dummies = pd.get_dummies(data = df['차량용도피해자'])
df_차량용도피해자_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_차량용도피해자_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,피해자_차량용도_기타,피해자_차량용도_렌터카,피해자_차량용도_버스,피해자_차량용도_보행자,피해자_차량용도_승용차,피해자_차량용도_이륜차,피해자_차량용도_자전거,피해자_차량용도_콘크리트믹서,피해자_차량용도_택시,피해자_차량용도_화물차
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,0,0,0,1,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,0,0,1,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,0,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,0,0,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,0,0,0,0,0,0,0

In [154]:
df.drop(['차량용도피해자_대분류','차량용도피해자_중분류','차량용도피해자'], axis = 1, inplace = True)

* 도로종류가 사고에 미치는 영향이 미미할 것이라 판단하여 전처리하지 않음. (컬럼제거)

In [155]:
df['도로종류'].unique()

array(['시도', '기타', '일반국도', '지방도', '군도'], dtype=object)

In [156]:
df.drop('도로종류', axis = 1, inplace = True)

* 도로형태_대분류, 도로형태 : 도형 + 대분류 + 도로형태 컬럼명으로 더미변수 생성 후 컬럼 제거

In [157]:
pd.DataFrame(df.groupby(['도로형태_대분류','도로형태'])['빈도 수'].count())

                    빈도 수
도로형태_대분류 도로형태
교차로      교차로내        679
         교차로부근       298
         교차로횡단보도내    165
기타       기타           35
기타/불명    기타/불명         8
단일로      기타단일로       541
         지하차도(도로)내    76
         횡단보도부근        3
         횡단보도상        11
불명       불명            3
주차장      주차장           4

In [158]:
#도로형태_교차로
df.loc[df['도로형태'] == '교차로내', '도로형태'] = '도형_교차로_교차로내'
df.loc[df['도로형태'] == '교차로부근', '도로형태'] = '도형_교차로_교차로부근'
df.loc[df['도로형태'] == '교차로횡단보도내', '도로형태'] = '도형_교차로_교차로횡단보도내'

#도로형태_기타
df.loc[df['도로형태'] == '기타', '도로형태'] = '도형_기타_기타'

#도로형태_기타/불명
df.loc[df['도로형태'] == '기타/불명', '도로형태'] = '도형_기타_기타'

# 도로형태_단일로
df.loc[df['도로형태'] == '기타단일로', '도로형태'] = '도형_단일로_기타단일로'
df.loc[df['도로형태'] == '지하차도(도로)내', '도로형태'] = '도형_단일로_지하차도(도로)내'
df.loc[df['도로형태'] == '횡단보도부근', '도로형태'] = '도형_단일로_횡단보도부근'
df.loc[df['도로형태'] == '횡단보도상', '도로형태'] = '도형_단일로_횡단보도상'

#도로형태_불명
df.loc[df['도로형태'] == '불명', '도로형태'] = '도형_기타_기타'


#도로형태_주차장
df.loc[df['도로형태'] == '주차장', '도로형태'] = '도형_주차장_주차장'

* '기타'로 통일 : 기타, 기타/불명, 불명 / 더미변수 생성 후에 '기타' 컬럼 제거 고려

In [159]:
df['도로형태'].unique()

array(['도형_교차로_교차로내', '도형_기타_기타', '도형_단일로_기타단일로', '도형_교차로_교차로부근',
       '도형_교차로_교차로횡단보도내', '도형_단일로_지하차도(도로)내', '도형_주차장_주차장',
       '도형_단일로_횡단보도상', '도형_단일로_횡단보도부근'], dtype=object)

In [160]:
도로형태_dummies = pd.get_dummies(df['도로형태'])
도로형태_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 도로형태_dummies, how = 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,피해자_차량용도_화물차,도형_교차로_교차로내,도형_교차로_교차로부근,도형_교차로_교차로횡단보도내,도형_기타_기타,도형_단일로_기타단일로,도형_단일로_지하차도(도로)내,도형_단일로_횡단보도부근,도형_단일로_횡단보도상,도형_주차장_주차장
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,1,0,0,0,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,1,0,0,0,0,0,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,1,0,0,0,0,0,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,1,0,0,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,1,0,0,0,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,0,1,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,1,0,0,0,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,0,1,0,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,1,0,0,0,0,0,0,0

In [161]:
df.drop(['도로형태_대분류','도로형태'], axis = 1, inplace = True) #도로형태 대분류, 도로형태 컬럼 제거

In [162]:
df['노인보호구역_여부'].unique()

array(['아니오', '예'], dtype=object)

In [163]:
#노인보호구역_여부 : 순서변수 ('아니오' : 1, '예' : 2)
mapping = {'아니오': 1,
           '예': 2}
df['노인보호구역_여부'] = df['노인보호구역_여부'].map(mapping)

In [164]:
df['노인보호구역_여부'].unique()

array([1, 2], dtype=int64)

In [165]:
df['어린이보호구역_여부'].unique()

array(['아니오', '예'], dtype=object)

In [166]:
mapping = {'아니오': 1,
           '예': 2}
df['어린이보호구역_여부'] = df['어린이보호구역_여부'].map(mapping)

In [167]:
df['어린이보호구역_여부'].unique()

array([1, 2], dtype=int64)

In [168]:
df['자전거도로_여부'].unique()

array(['아니오', nan, '예'], dtype=object)

In [169]:
df['자전거도로_여부'] = df['자전거도로_여부'].fillna('아니오')

* 일단 nan값을 '아니오'로 채워놓음. 검토 필요.

In [170]:
df['자전거도로_여부'].unique()

array(['아니오', '예'], dtype=object)

In [171]:
# 자전거도로 '아니오' : 1, '예' : 2 (순서 변수)
mapping = {'아니오' : 1, 
           '예' : 2 }
df['자전거도로_여부'] = df['자전거도로_여부'].map(mapping)

In [172]:
df['자전거도로_여부'].unique()

array([1, 2], dtype=int64)

In [173]:
#'도로선형_대분류', '도로선형_중분류', '도로선형' : 중분류 고려 x / 더미변수 생성
pd.DataFrame(df.groupby(['도로선형_대분류', '도로선형_중분류', '도로선형'])['빈도 수'].count())

                            빈도 수
도로선형_대분류 도로선형_중분류 도로선형
기타구역     기타구역     기타/서비스구역    17
직선       직선       내리막        101
                  오르막         67
                  평지        1575
커브ㆍ곡각    우        내리막          7
                  오르막          7
                  평지          22
         좌        내리막          4
                  오르막          7
                  평지          16

In [174]:
#도로선형_기타구역
df.loc[(df['도로선형_대분류'] == '기타구역') & (df['도로선형'] == '기타/서비스구역'), '도로선형'] = '도로선형_기타_기타'

# 도로선형_직선
df.loc[(df['도로선형_대분류'] == '직선') & (df['도로선형'] == '내리막'), '도로선형'] = '도로선형_직선_내리막'
df.loc[(df['도로선형_대분류'] == '직선') & (df['도로선형'] == '평지'), '도로선형'] = '도로선형_직선_평지'
df.loc[(df['도로선형_대분류'] == '직선') & (df['도로선형'] == '오르막'), '도로선형'] = '도로선형_직선_오르막'

#도로선형_커브곡각
df.loc[(df['도로선형_대분류'] == '커브ㆍ곡각 ') & (df['도로선형'] == '평지'), '도로선형'] = '도로선형_커브곡각_평지'
df.loc[(df['도로선형_대분류'] == '커브ㆍ곡각 ') & (df['도로선형'] == '내리막'), '도로선형'] = '도로선형_커브곡각_내리막'
df.loc[(df['도로선형_대분류'] == '커브ㆍ곡각 ') & (df['도로선형'] == '오르막'), '도로선형'] = '도로선형_커브곡각_오르막'

In [175]:
df['도로선형'].unique()

array(['도로선형_직선_내리막', '도로선형_직선_평지', '평지  ', '도로선형_직선_오르막', '도로선형_기타_기타',
       '도로선형_커브곡각_오르막', '도로선형_커브곡각_내리막'], dtype=object)

In [176]:
도로선형_dummies = pd.get_dummies(df['도로선형'])
도로선형_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, 도로선형_dummies, how = 'outer', on = 'TAAS사고관리번호')

In [177]:
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,도형_단일로_횡단보도부근,도형_단일로_횡단보도상,도형_주차장_주차장,도로선형_기타_기타,도로선형_직선_내리막,도로선형_직선_오르막,도로선형_직선_평지,도로선형_커브곡각_내리막,도로선형_커브곡각_오르막,평지
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,0,1,0,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,0,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,0,0,0,0,1,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,0,0,0,0,1,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,1,0,0,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,0,0,0,0,1,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,0,0,0,0,1,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,0,0,0,0,1,0,0,0

In [178]:
df.drop(['도로선형_대분류', '도로선형_중분류', '도로선형'], axis = 1, inplace = True)

* '기상상태','노면상태_대분류', '노면상태', '교차로형태_대분류', '교차로형태',

In [179]:
df['기상상태'].unique()

array(['맑음', '비', '흐림', '안개', '기타/불명'], dtype=object)

In [180]:
#기상상태 : 더미변수
df_기상상태_dummies = pd.get_dummies(df['기상상태'])
df_기상상태_dummies.rename(columns  = {'기타/불명' : '기상상태_기타'}, inplace = True)
df_기상상태_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호'] #키 생성
df = pd.merge(df, df_기상상태_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,도로선형_직선_오르막,도로선형_직선_평지,도로선형_커브곡각_내리막,도로선형_커브곡각_오르막,평지,기상상태_기타,맑음,비,안개,흐림
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,0,0,0,0,1,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,1,0,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,1,0,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,1,0,0,0,0,1,0,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,1,0,0,0,0,1,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,0,0,0,0,1,0,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,1,0,0,0,0,1,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,1,0,0,0,0,1,0,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,1,0,0,0,0,1,0,0,0

In [181]:
df.drop('기상상태', axis = 1, inplace = True) #기상상태 컬럼 제거

In [182]:
#노면상태_대분류, 노면상태 : 컬럼 합쳐서 전처리
df['노면상태_대분류'].unique()

array(['포장', '비포장'], dtype=object)

In [183]:
df['노면상태'].unique()

array(['건조', '젖음/습기', '기타'], dtype=object)

In [184]:
pd.DataFrame(df.groupby(['노면상태_대분류','노면상태'])['빈도 수'].count())

                빈도 수
노면상태_대분류 노면상태
비포장      건조        1
         젖음/습기     1
포장       건조     1737
         기타        8
         젖음/습기    76

In [185]:
df.loc[(df['노면상태_대분류'] == '비포장') & (df['노면상태'] == '건조'), '노면상태'] = '비포장_건조'
df.loc[(df['노면상태_대분류'] == '비포장') & (df['노면상태'] == '젖음/습기'), '노면상태'] = '비포장_젖음/습기'
df.loc[(df['노면상태_대분류'] == '포장') & (df['노면상태'] == '건조') , '노면상태'] = '포장_건조'
df.loc[(df['노면상태_대분류'] == '포장') & (df['노면상태'] == '기타') , '노면상태'] = '포장_기타'
df.loc[(df['노면상태_대분류'] == '포장') & (df['노면상태'] == '젖음/습기') , '노면상태'] = '포장_젖음/습기'

In [186]:
df_노면상태_dummies = pd.get_dummies(df['노면상태'])
df_노면상태_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_노면상태_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,기상상태_기타,맑음,비,안개,흐림,비포장_건조,비포장_젖음/습기,포장_건조,포장_기타,포장_젖음/습기
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,1,0,0,0,0,0,1,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,1,0,0,0,0,0,1,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,1,0,0,0,0,0,1,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,1,0,0,0,0,0,1,0,0
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,1,0,0,0,0,0,1,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,1,0,0,0,0,0,1,0,0
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,1,0,0,0,0,0,1,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,1,0,0,0,0,0,1,0,0
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,1,0,0,0,0,0,1,0,0

In [187]:
df.drop(['노면상태_대분류','노면상태'], axis = 1, inplace = True)

* 교차로형태_대분류, 교차로형태 : 교차로형태 컬럼으로 통일

In [188]:
pd.DataFrame(df.groupby(['교차로형태_대분류','교차로형태'])['빈도 수'].count())

                      빈도 수
교차로형태_대분류 교차로형태
교차로       교차로 - 사지     718
          교차로 - 삼지     373
          교차로 - 오지이상    47
          교차로 - 회전       4
교차로아님     교차로아님        681

In [189]:
df_교차로형태_dummies = pd.get_dummies(df['교차로형태'])
df_교차로형태_dummies['TAAS사고관리번호'] = df['TAAS사고관리번호']
df = pd.merge(df, df_교차로형태_dummies, how= 'outer', on = 'TAAS사고관리번호')
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,비포장_건조,비포장_젖음/습기,포장_건조,포장_기타,포장_젖음/습기,교차로 - 사지,교차로 - 삼지,교차로 - 오지이상,교차로 - 회전,교차로아님
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,1,0,0,1,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,1,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,1,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,1,0,0,0,0,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,1,0,0,1,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,1,0,0,0,0,0,0,1
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,1,0,0,1,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,1,0,0,0,0,0,0,1
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,1,0,0,0,0,1,0,0

In [190]:
df.drop(['교차로형태_대분류','교차로형태'], axis = 1, inplace = True)

In [191]:
df

,index,TAAS사고관리번호,발생지_시도,발생지_시군구,X_POINT,Y_POINT,요일,주야,사고내용,연령가해자,...,비포장_건조,비포장_젖음/습기,포장_건조,포장_기타,포장_젖음/습기,교차로 - 사지,교차로 - 삼지,교차로 - 오지이상,교차로 - 회전,교차로아님
0,0,2020082200100432,충북,청주시,1000111.0,1845339.0,6,1,2,1,...,0,0,1,0,0,1,0,0,0,0
1,1,2020080100100116,충북,청주시,993596.0,1848445.0,6,1,2,2,...,0,0,1,0,0,0,1,0,0,0
2,2,2020092600100236,충북,청주시,995526.0,1847649.0,6,1,2,7,...,0,0,1,0,0,0,1,0,0,0
3,3,2020121200100323,충북,청주시,995679.0,1851636.0,6,1,2,5,...,0,0,1,0,0,0,0,0,0,1
4,4,2020062700100313,충북,청주시,993695.0,1848615.0,6,1,1,5,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,2018041900100012,충북,청주시,998267.0,1852140.0,4,2,3,5,...,0,0,1,0,0,1,0,0,0,0
1819,1819,2018071900100710,충북,청주시,997198.0,1847791.0,4,2,2,6,...,0,0,1,0,0,0,0,0,0,1
1820,1820,2018011300100473,충북,청주시,998501.0,1852654.0,6,2,2,4,...,0,0,1,0,0,1,0,0,0,0
1821,1821,2017102000100588,충북,청주시,993500.0,1848011.0,5,2,2,4,...,0,0,1,0,0,0,0,0,0,1
1822,1822,2017091300100523,충북,청주시,995354.0,1848473.0,3,2,2,2,...,0,0,1,0,0,0,0,1,0,0

In [192]:
df.to_csv("C:/Users/user/Desktop/자전거PM사고_청주_cleaned.csv",header = True, index = False, encoding = 'cp949')